ministryofjustice/hmpps-activities-management-api

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Activity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityCategory.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityInstance.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityPay.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityPrisoner.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityTier.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityWaiting.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Attendance.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/Activity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivityInstance.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivityPrisoner.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivityTier.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivityWaiting.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/TransformFunctions.kt, src/main/resources/migration/common/V1__baseline.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/ActivityRepositoryTest.kt
* Removed redundant `prison_code` from tables, entities and model objects that did not need it.
* Removed redundant location info - now only in ACTIVITY_SESSION.
* Linked the waiting list to the ACTIVITY instead of ACTIVITY_SESSION.
* Altered some column names for consistency of tense, meaning.
* Added transforms for entity-> model waiting list.
* Added indexes where needed - particularly on the referencing side of FK relationships.
* Adjusted ACTIVITY_TIER so it has an ID, CODE and DESC like categories (tiers can be 1, 2 or FOUNDATION)
* Adjusted tests to pass.
I've updated the model diagram to reflect the same changes - so they are now in line though we could use IJ to generate the  diagrams.
THIS IS A BREAKING CHANGE - so schema will need to be dropped prior to deploying.
=> SAA-65 data model checks and amendments

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/ActivityRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/TransformFunctions.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/TransformFunctionsTest.kt
Changes include:
- New service for retrieval of a single activity by its ID.
- Simple service test coverage as well as transformation test coverage.
=> SAA-62 introduction of activity service for retrieval of a single activity by ID.

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/config/ControllerAdvice.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/config/OpenApiConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/Activity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivityInstance.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivityPrisoner.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivitySession.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivityWaiting.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/ActivityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/TransformFunctionsTest.kt
Changes:
- New endpoint for retrieval of a singe activity by its ID.
- Added Open API/Swagger artifacts to start the process of documenting the API.
- Minor refactoring.
=> SAA-63 introduction of activity rest controller with simple endpoint for retrieval of an activity by an ID.

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/Activity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivityCategory.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivityEligibility.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivityInstance.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivityPay.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivityPayBand.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivityPrisoner.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivitySession.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivityTier.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivityWaiting.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/EligibilityRule.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/TransformFunctions.kt, src/main/resources/migration/common/V1__baseline.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/health/JwtAuthHelper.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/ActivityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/wiremock/OauthMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/TransformFunctionsTest.kt, src/test/resources/test_data/clean-all-data.sql, src/test/resources/test_data/seed-activity-id-1.sql, src/test/resources/test_data/seed-activity-id-2.sql, src/test/resources/test_data/seed-reference-data.sql
This is a work in progress PR for the introduction of integration testing of activities and the initial underlying DB model.
**Note: this contains a breaking change to the data model which results in a change to the existing dev DB.  The dev DB will need to be dropped prior to merging into main.**
=> SAA-64 WIP introduction of integration test for testing  activities and the underlying DB model.

.circleci/config.yml
Include the integration tests as part of the Cirlce CI build pipeline.
=> SAA-68 now running the integration tests as part of the CI build pipeline.

helm_deploy/hmpps-activities-management-api/values.yaml
This is related to this cloud platform PR [here](https://github.com/ministryofjustice/cloud-platform-environments/pull/8821).
=> SAA-83 adding helm config to pull in queue configuration environment vars.

.circleci/config.yml
=> SAA-103 updating to the latest HMPPS Circle orb to support changes to Docker in Circle CI.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/common/TimeSlot.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ScheduledInstance.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityScheduleController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityScheduleService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/common/TimeSlotTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityScheduleIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ExtensionFunctions.kt, src/test/resources/test_data/seed-activity-id-1.sql
=> SAA-109 extending retrieval of activity schedules endpoint to filter by time slot.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/config/OpenApiConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Attendance.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ScheduledInstance.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/Attendance.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/AttendanceReason.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ScheduledInstance.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/ScheduledInstanceRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ScheduledInstanceController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AttendancesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/TransformFunctions.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/ActivityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/AttendanceIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ScheduledInstanceControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/TransformFunctionsTest.kt, src/test/resources/test_data/clean-all-data.sql, src/test/resources/test_data/seed-activity-id-1.sql
Adds new endpoint for retrieval of attendances for marking attendance:
`/scheduled-instances/{instanceId}/attendances`
=> SAA-118 initial commit for new endpoint for retrieval of attendance records for a scheduled activity.

util_scripts/create_attendance_records.sql
A simple utility script to aid with creation of attendance records until we have the scheduled job in place which will ultimately be responsible for the creation of them.
Note: it doesn't populate pay rates. This is yet to be done.
=> SAA-129 simple util SQL script for creating attenadnace records.  It does not handle pay rates at the moment.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/common/LocalDateExt.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/common/LocalDateIterator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/common/LocalDateRange.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivityLite.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivityScheduleInstance.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivityScheduleLite.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/ScheduledInstanceRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityScheduleInstanceController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledInstanceService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/TransformFunctions.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/common/LocalDateRangeTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ScheduledInstanceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityScheduleInstanceIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityScheduleInstanceControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledInstanceFixture.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledInstanceServiceTest.kt, src/test/resources/test_data/seed-activity-id-3.sql
New endpoint, service, named query
Added mapstruct (experimental)
=> SAA-138 API get prisoners scheduled activity instances

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/CreateAttendanceRecordsJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/JobTrigger.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AttendancesService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/CreateAttendanceRecordsJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/JobTriggerTest.kt
Getting the initial stubbed wiring in place for the creation of attendance records (via a K8's cronjob).
=> SAA-176 intilial API wiring for creation of attendance records job. WIP.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/config/ResourceServerConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivitySchedule.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivityScheduleLite.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/PrisonerScheduledEvents.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledEventService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctions.kt, src/main/resources/application-local.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityScheduleTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ScheduledEventIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledEventServiceTest.kt
Altered ScheduledEventService to use activities management service for 'activities' if prison hasn't been rolled out
=> SAA-184 AM Events Endpoint: Incorporate activities (AM API)

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ScheduledEvent.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledEventService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctions.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ScheduledEventIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledEventFixture.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledEventServiceTest.kt
Altered ScheduleEventService to call PrisonRegimeService for event priorities
Added event priorities to response
=> SAA-199 Decorate scheduled event endpoint with event priorities

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Activity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityCategory.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivityLite.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/response/ActivityCategory.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledEventService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctions.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityCategoryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityScheduleTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/ActivityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityCategoryIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/PrisonIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityCategoryControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/PrisonControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledEventServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledInstanceFixture.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctionsTest.kt
Added ActivityCategory to ActivityLite
Added code property to ActivityCategory model
Make sure default priority is returned for event type when no categories match
Consider event categories when adding priority to an event
=> SAA-199 Event category priorities

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/LocationPrefixController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/LocationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/LocationPrefixIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/LocationPrefixControllerTest.kt
New activities management api : Get location prefix by group (migrated from whereabouts API)
=> SAA-221 Create Activities Management API location endpoints

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/config/ControllerAdvice.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/request/PrisonerAllocationRequest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityScheduleControllerTest.kt
Example response on constraint violation(s):
{
"status": 400,
"errorCode": null,
"userMessage": "One or more constraint violations occurred",
"developerMessage": "Pay band cannot be blank, Prisoner number cannot be blank",
"moreInfo": null
}
=> SAA-247 add simple controller advice for constraint violations and improving messages for allocation request.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Activity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/Activity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivityLite.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/request/ActivityCreateRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctions.kt, src/main/resources/migration/common/V1__baseline.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityServiceTest.kt, src/test/resources/__files/activity/activity-create-request-2.json
tier and description become optional
Also SAA-262 - unique constraint added to prison code and summary
=> SAA-259 activity data model changes

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityIntegrationTest.kt
=> SAA-268 activity max length constraints

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivitySchedule.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Allocation.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/RolloutPrison.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/Allocation.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/RolloutPrison.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityScheduleService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctions.kt, src/main/resources/migration/common/V1__baseline.sql, src/main/resources/migration/data/R__2_4__allocations.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityScheduleTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/ActivityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/PrisonerAllocationIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctionsTest.kt, src/test/resources/test_data/seed-activity-id-1.sql, src/test/resources/test_data/seed-activity-id-2.sql, src/test/resources/test_data/seed-activity-id-3.sql, src/test/resources/test_data/seed-activity-id-4.sql, src/test/resources/test_data/seed-activity-id-5.sql, src/test/resources/test_data/seed-activity-id-6.sql, src/test/resources/test_data/seed-activity-id-8.sql
Add booking id to allocations
Also make rollout prison date optional
=> SAA-275 Add booking id to allocations

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/request/ActivityCreateRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/ActivityRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/PrisonController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/PrisonIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/PrisonControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityServiceTest.kt, src/test/resources/__files/activity/activity-create-response-1.json
New activities endpoint - all activities for prison
=> SAA-279 Basic activities dashboard

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctions.kt
Urgent review please - for Show n Tell in the morning.
=> SAA-299: Bug fix check nulls on end time.

src/main/resources/migration/common/V1__baseline.sql
**DO NOT MERGE WITHOUT DROPPING DEV DB FIRST**
=> SAA-303 updating the scheduled activites view on the back of start and end dates being added to the schedule.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/PrisonPayBand.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/PrisonPayBand.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/PrisonPayBandRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/PrisonController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/PrisonRegimeService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctions.kt, src/main/resources/migration/common/V1__baseline.sql, src/main/resources/migration/data/R__2_8__prison_pay_bands.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/ActivityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/PrisonPayBandIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/PrisonControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/PrisonRegimeServiceTest.kt, src/test/resources/test_data/clean-all-data.sql, src/test/resources/test_data/seed-reference-data.sql
**DO NOT MERGE - DEV DB DROP IS REQUIRED PRIOR TO MERGE!**
=> SAA-311 adding new feature for the retrieval of prison specfic pay bands or a bunch of defaults if none configured.

build.gradle.kts
Bumping to latest 3rd party dependencies where available.
=> SAA-366 chore updating 3rd party dependencies.

util_scripts/bulk-allocate.sh, util_scripts/bulk-prisoner-allocate.sh
Utility script to help support bulk allocations of prisoners to activity schedules when migrating a prison from NOMIS to our new service.
Note to run this script you do not need to keep any environment variables (secrets) on your machine.  It will pull in the necessary secrets as required as upon execution.
=> SAA-365 bash util script for bulk allocation of offenders.

src/main/resources/migration/data/R__1_2__activity_categories.sql, src/main/resources/migration/data/R__1_3__activity_tiers.sql, src/main/resources/migration/data/R__1_4__attendance_reasons.sql, src/main/resources/migration/data/R__2_2__schedules.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityCategoryIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/PrisonIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/testdata/IntegrationTestActivityCategories.kt, src/test/resources/test_data/seed-activity-id-2.sql, src/test/resources/test_data/seed-reference-data.sql
**DO NOT MERGE, CONTAINS DB SEED DATA CHANGES**
Updating our seed data to be inline with the data that is NOMIS.
The main driver for this being to aid synchronisation of our data with NOMIS.  The Syscon team are not able to correctly map our activities to NOMIS due to not matching up with values in NOMIS.
=> SAA-378 tidy up seed data to be inline with NOMIS data for the sync process

util_scripts/bulk-prisoner-allocate.sh
Updated to create timestamped success and failure files for bulk allocations:
Input file:
```
1,A5193DY,12
1,G4793VF,12
1,A9477DY,12
1,D7193DY,12
1,K4793JH,12
1,B8455DY,12
```
Success example (allocation-successes-2023-02-22T17-14-24.txt):
```
1,D7193DY,12
1,K4793JH,12
1,B8455DY,12
```
Failure output example (allocation-failures-2023-02-22T17-14-24.txt):
```
1,A5193DY,12 - ["Prisoner 'A5193DY' is already allocated to schedule Entry level Maths 1."]
1,G4793VF,12 - ["Prisoner 'G4793VF' is already allocated to schedule Entry level Maths 1."]
1,A9477DY,12 - ["Prisoner 'A9477DY' is already allocated to schedule Entry level Maths 1."]
```
=> SAA-375 updated to generate timestamped success and failure files on bulk allocation.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/EventCategory.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ScheduledEvent.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/PrisonRegimeService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledEventService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/PrisonApiTransformations.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctions.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/PrisonRegimeServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledEventServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/PrisonApiTransformationsKtTest.kt
Part 1 is really a code moving exercise with a little bit of change as well.
Part 2 will be bringing the EventCategory inline with our actual activity categories which have changed/moved on.
=> SAA-542 first step towards refactoring code around event category prioritisation.

build.gradle.kts
springdoc fixed in https://github.com/springdoc/springdoc-openapi/issues/2185
=> SDIT-423 Use latest springdoc including required fix

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Allocation.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ScheduledInstance.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/AllocationRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/OffenderReleasedFromPrisonService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityScheduleTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AllocationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/OffenderReleasedFromPrisonIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/OffenderReleasedFromPrisonServiceTest.kt
Service layer and Domain changes to support an offender being temporarily released prison (events).
The incoming event work to call this will be done separately.
=> SAA 563 temporary release offender from prison

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Attendance.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/request/AttendanceUpdateRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AttendancesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctions.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/AttendanceIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/AttendanceControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AttendancesServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctionsTest.kt
Display history records in reverse chronological order
Pay content should be the Amount or ‘none’
=> SAA-587: minor issues with the attend journey

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ManageAttendancesService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ManageAttendancesServiceTest.kt
Adds support for creating attendance records for scheduled instances which have been cancelled
=> SAA-433: Cater for cancellations when creating attendance records

applicationinsights.dev.json, applicationinsights.json, src/main/resources/logback-spring.xml
Recommended changes - from others with the same issues.
=> SAA-609: Updates to logback for app insights changes

src/main/resources/migrations/common/V2023.06.02__change_attendance_reason_descriptions.sql
Updates cancelled status description
=> SAA-734: Updates cancelled status description

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/request/AppointmentCreateRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/request/BulkAppointmentsRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AppointmentService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/AppointmentModelFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/request/AppointmentCreateRequestTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/request/BulkAppointmentCreateRequestTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AppointmentServiceTest.kt
Adds support for comments on bulk appointments
=> SAA-731: Bulk appointment comments

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Attendance.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AttendanceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/AttendanceIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AttendancesServiceTest.kt, src/test/resources/test_data/seed-activity-for-attendance-marking.sql, src/test/resources/test_data/seed-activity-update-slot.sql
Simple change to add validation to attendance marking. Marking attendance that's not editable will now throw an exception.
=> SAA-890: Adds validation to attendance marking

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Attendance.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AttendancesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctions.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/AttendanceControllerTest.kt
Removes duplicate transformer method and fixes `caseNoteText` and `editable` fields.
=> SAA-872: Removes duplicate transformer

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/config/ClientTrackingConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/MigrateAppointmentController.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/MigrateAppointmentIntegrationTest.kt
- NOMIS_APPOINTMENTS is a role, not an authority
- Added client id to app insights custom dimensions suggested by Syscon
=> Using hasRole for migrate appointment authorisation

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivitySchedule.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityScheduleSlot.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityScheduleSlotTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityScheduleTest.kt
Adds validation for new entity fields.
=> SAA-998: Validation

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivitySchedule.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityScheduleTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/ActivityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityServiceTest.kt
This is a small change to add the helper function needed to retrieve the week number for a given date of a multi-week schedule.
It implements this in the `ActivitySchedule.addInstances()` method in the `ActivityService` class.
=> SAA-996: Multi-week schedule model updates

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Activity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Allocation.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AuditableEntityListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/audit/AuditableEvent.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/audit/PrisonerDeallocatedEvent.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AuditService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/AuditTransformations.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AuditableEntityListenerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/InboundEventsIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/audit/PrisonerDeallocatedEventTest.kt
Deallocations are now audited upon a prisoner being permanently released from prison.
=> SAA-1016 changes to audit deallocation of a prisoner upon being permanently released.

src/main/resources/migrations/prod/V2023.07.25__rollout_risley.sql
and production rollout once date and pay bands have been agreed
=> SAA-767: Migration to support Risley rollout testing on pre prod

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AppointmentService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AppointmentServiceTest.kt
Adds validation to prevent creation of extremely large repeat appointments
=> SAA-997: Limit appointment occurrence allocations

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/PrisonApiTransformations.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AppointmentOccurrenceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AppointmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/BulkAppointmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctionsTest.kt
Minor content changes for missing migration data.
=> SAA-941: Appointments content updates

src/main/resources/application.yml
=> SAA-1086 small change which sorts the endpoints/controllers alphabetically when viewing the Swagger UI.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/WaitingListService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/OffenderReleasedEventHandler.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/InboundEventsIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/OffenderReleasedEventHandlerTest.kt, src/test/resources/test_data/seed-offender-for-release.sql
=> SAA-1108 declining affected waiting list records on receipt of prisoner release event.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityCategoryController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityScheduleController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/AllocationController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ScheduledInstanceController.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityCategoryControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityScheduleControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/AllocationControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ScheduledInstanceControllerTest.kt
Adds `NOMIS_ACTIVITIES` role to required endpoints
=> SAA-1079: Added ROLE_NOMIS_ACTIVITIES role

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/AppointmentInstanceController.kt, src/main/resources/migrations/common/V2023.09.13__index_appointment_soft_delete_columns.sql
- Add indexes on columns used in soft delete where clauses
- Add NOMIS_ACTIVITIES role to endpoint used by sync
=> SAA-1162: Indexes and roles

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AttendancesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledInstanceService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AttendancesServiceTest.kt
Not 100% sure if this will resolve it so small PR to trial it.
=> SAA-1208 taking out transactional annotation in effort to resolve timing issues with flushing attendance changes to DB for raising events.

src/main/resources/migrations/common/V2023.09.19__update_risley_pay_bands.sql
Second attempt. Now with correct values for updating allocations :-)
=> SAA-1204 risley pay band updates

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AppointmentService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AppointmentServiceUpdateTest.kt
Adds validation for making large modifications to existing appointments
=> SAA-1085: Added validation for large updates to existing appointments

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/InboundEventsListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/InboundEventsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/OutboundEventsPublisher.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/ActivitiesChangedEventHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/InterestingEventHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/OffenderReceivedEventHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/OffenderReleasedEventHandler.kt
Changing logging calls around event handling to use debug log level to reduce the amount of unwanted noise in the production logs.
=> SAA-1252 reducing the event logging noice in the API.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityScheduleService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AttendancesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledInstanceService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/telemetry/TelemetryEvent.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/telemetry/TelemetryEventConstants.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/telemetry/TelemetryTransformFunctions.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityScheduleServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AttendancesServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledInstanceServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/telemetry/ActivitiesTelemetryTransformFunctionsTest.kt
Adds new `RECORD_ATTENDANCE` event as well as updating the `CREATE_ALLOCATION` event with required properties.
=> SAA-1231: Added API metrics events

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/AppointmentMetricsJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/JobTriggerController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/DailyAppointmentMetricsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/DailyAppointmentsMetricsJobIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/wiremock/PrisonApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/AppointmentMetricsJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/JobTriggerControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/DailyAppointmentMetricsServiceTest.kt, src/test/resources/test_data/seed-appointments-daily-metrics.sql
- Fixes appointments daily metrics job by adding transactional annotation
- Refactored job and service
- Improves unit test coverage
- Improved integration test and seed data
=> SAA-1230: Fix appointments daily metrics

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AppointmentAttendanceSummary.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AppointmentAttendeeSearch.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AppointmentSearch.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/AppointmentAttendanceSummary.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/AppointmentAttendanceSummaryRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/AppointmentController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AppointmentAttendanceService.kt, src/main/resources/migrations/common/V2023.10.10__v_appointment_attendance_summary.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AppointmentAttendanceSummaryTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/ActivityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/AppointmentEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/AppointmentModelFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/AppointmentAttendanceIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/AppointmentControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AppointmentAttendanceServiceTest.kt, src/test/resources/test_data/seed-appointment-attendance-summaries.sql, src/test/resources/test_data/seed-appointment-attendance.sql, src/test/resources/test_data/seed-appointments-daily-metrics.sql, src/test/resources/test_data/seed-manage-appointments-job.sql
Adds GET /appointments/{prisonCode}/attendance-summaries endpoint for listing attendance
=> SAA-1284: Appointment attendance summary endpoint

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AllocationsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/AllocationIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AllocationServiceTest.kt
This was missed off the original bug fix PR [here](https://github.com/ministryofjustice/hmpps-activities-management-api/pull/619)
=> SAA-1282 missed off original PR. We now also need to raise allocation amend events when we update allocations.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ManageAllocationsService.kt
Will look to cleanup logging once I have got to the bottom of current issues with expiration of allocations process.
=> SAA-1221 increasing logging around allocation expiration to help identify potential issues.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/request/WaitingListSearchRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/WaitingListRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/WaitingListSearchSpecification.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/WaitingListApplicationController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/WaitingListService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/WaitingListApplicationIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/request/WaitingListSearchRequestTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/WaitingListApplicationControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/WaitingListServiceTest.kt, src/test/resources/test_data/seed-activity-id-22.sql, src/test/resources/test_data/seed-activity-id-26.sql
Adds new endpoint, `POST/waiting-list-applications/{prisonCode}/search` to support the searching of waiting list applications
=> SAA-1262: Added waiting list search endpoint

src/main/resources/whereabouts/patterns/groups.properties
Just a maintenance task to mirror changes that are made to Whereabouts location config.
=> SAA-1343: Add HB8 for Ranby - keeping locations config in sync with Whereabouts.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Appointment.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AppointmentCreateDomainService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/MigrateAppointmentController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AppointmentSeriesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/MigrateAppointmentService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AppointmentCreateDomainServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AppointmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/MigrateAppointmentControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AppointmentSeriesServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/MigrateAppointmentServiceTest.kt
**LOW RISK**
This does change the creation process for appointments but only for migrated appointments initially to test isolation. Therefore this is low risk rather than higher.
=> SAA-1256: Refactor create appointment for migrated appointments

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/InterestingEventHandler.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/InboundEventsIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/wiremock/PrisonApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/InterestingEventHandlerTest.kt
**LOW RISK**
This changes the interesting event back to using prison-api instead of prisoner-search due a race condition happening with incentive events being processed and the information related to those events not being quite ready in prisoner-search due to timing.
=> SAA-1334 this is changing the interesting event handler back to prison-api due a race condition with prisoner-search.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AppointmentCreateDomainService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/CreateAppointmentsJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/audit/AppointmentSeriesCreatedEvent.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AppointmentSeriesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AppointmentSetService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/MigrateAppointmentService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AppointmentCreateDomainServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/AppointmentModelFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/CreateAppointmentsJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/audit/AppointmentSeriesCreatedEventTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AppointmentSeriesServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/MigrateAppointmentServiceTest.kt
**MEDIUM RISK**
This is the final create appointment series refactor. It unblocks all further changes to the creation process and the move to publishing sync messages post transaction.
=> SAA-1256: Refactor create appointment series sync and async

helm_deploy/hmpps-activities-management-api/values.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/MonitoringService.kt
Small change to add extra logging in monitoring service to confirm it is at least being called on a job failure.
=> SAA-1357 increase logging to help with debugging monitoring service behaviour.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ManageAttendancesService.kt
Just adding some simple logging to log number of attendances created for a prison when the job runs.
=> SAA-1380 added attendance counter log statement.

Dockerfile, run.sh
=> SAA-1427 updating Docker file to pull in the JAVA_OPTS env with running the service to pick memory settings.

Dockerfile
=> SAA-1427 updating Docker file to pull in the JAVA_OPTS env with running the service to pick mememory settings.

helm_deploy/values-dev.yaml
Turn offender merge updates on in DEV only.
=> SAA-1412 enable feature offender merge DB updates in dev.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/config/WebClientConfiguration.kt
Prior to this change our web client configs have no timeouts applied.
This has resulted in some connections/calls to external API's to hang around for an extremely long duration before timing out.  As a result this will be impacting our API hanging onto connections/resources.
This change adds some sensible defaults which if we decide to can be overridden via environment variables.
=> SAA-1466 adding timeouts to our web clients to external API's to prevent long running (waiting) connections.

helm_deploy/hmpps-activities-management-api/values.yaml, helm_deploy/values-dev.yaml
Need to bump the available memory in dev.  Starting to see out of memory errors as more data makes its way into the service.
=> SAA-1481 increasing available memory in dev to stop out of memory errors.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/CandidatesService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/ActivityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/CandidatesServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/PrisonerSearchPrisonerFixture.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/WaitingListServiceTest.kt
Updates behaviour of in work filter to consider "not in work" activity allocations.
=> SAA-1460: Not in work activities filter

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/config/WebClientConfiguration.kt
Adding to configuration logging for monitoring purposes to see if we need the config the way it is or whether it can/should be changed.
=> SAA-1502 adding logging to the WebClientConfiguration to monitor usage/instance creation in particular for @RequestScope beans.

.circleci/config.yml
Change to use new activities and appointments team alerts channel.
=> SAA-1548 use team alerts channel.

.circleci/config.yml
Not 100% sure this will fix it.  Either way it should not be using JDK 17, it should be 21.
=> SAA-1550 specifiying the Java version for the OWASP task to see if the fixes it. It looks like it is using the wrong version looking at Circle CI.

build.gradle.kts, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/EndpointSecurityCheck.kt
One of the tests had to be updated as a result of bumping the SQS library, it is not cause for concern.  I have commented on the test impacted.
=> SAA-1555 update dependencies to resolve OWASP security job failure in the CI pipeline.

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AppointmentUpdateDomainService.kt
- Clear 3 CVEs
- Resolve subsequent issues with child entities following `saveAndFlush`
=> SAA-1575: Update dependencies to clear CVEs

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctions.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctionsTest.kt
Shwo in cell appointment locations for attendance.
=> SAA-1599: Show in cell locations for appointments in activities attendance

helm_deploy/values-dev.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/client/casenotesapi/api/CaseNotesApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Job.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/ManageAllocationsJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/SafeJobRunner.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/JobsTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/ManageAllocationsJobTest.kt
The retry has already been applied to attendance creation and is out in production.
This change adds it to the allocation/deallocation jobs.
=> SAA-1627 add retry to allocations jobs.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityServiceTest.kt
Updating error content as per team review session amendments
=> SAA-1128: Amend error content

build.gradle.kts
Reverts ministryofjustice/hmpps-activities-management-api#849
=> Revert "Update dependency io.opentelemetry.instrumentation:opentelemetry-instrumentation-annotations to v2"

helm_deploy/hmpps-activities-management-api/Chart.yaml
Reverts ministryofjustice/hmpps-activities-management-api#848
=> Revert "Update Helm release generic-service to v3"

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityScheduleSlot.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivityScheduleSlot.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityScheduleTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctionsTest.kt
=> SAA-494: Add timeslot to activity schedule slot info

src/main/resources/migrations/prod/V2024.06.28__fix_attendance_record.sql
Change the issue_payment to be true as this has already been paid
=> SAA-1825: Fix attendance record

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/AllocationRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityScheduleController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/CandidatesService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/CandidatesServiceTest.kt
Reverts ministryofjustice/hmpps-activities-management-api#950
=> Revert "SAA-1839 improve performance (experimental)"

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityScheduleController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/CandidatesService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityScheduleIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/CandidatesServiceTest.kt, src/test/resources/test_data/seed-candidates.sql
slimmed down version after reverting previous PR
this now has test data that will actually run the relevant code.  
JPA query can be looked into next
=> SAA-1839 candidates performance (experimental)

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/CandidatesService.kt
use sequence rather than list, and any rather than none, and avoid filtering allocations if flag is null
=> SAA-1839 optimize again

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivitySchedule.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/MigrateActivityService.kt, src/main/resources/application.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ExperimentalMigrateIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/MigrateActivityServiceTest.kt, src/test/resources/__files/incentivesapi/incentive-levels-IWI.json, src/test/resources/application-experimental.yml, src/test/resources/samples/iwi_activity.json, src/test/resources/test_data/seed-migrate-experiment.sql
Can expand on this,  ie include exclusions, run scheduler later in test and so on.  and probably just put all the requests in json, and load from file at some point.
sample output added from the created activity bypassing exception
=> SAA-1890 iwi test rig, flag to skip exception

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivitySchedule.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivityScheduleSlot.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/Slot.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AllocationsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/AllocationIntegrationTest.kt
very odd.  code has always been illegal, reverted to an older api commit, added a specific test to set the field daysOfWeek and it errors.
As to how it seems to work in dev, when i revert latest is odd.  OpenAPI will pick up daysOfWeek as its a get, and therefore sends it to the api, which obviously can not convert it.
=> UI has always been making an illegal call, but now its able to report it

src/main/resources/migrations/common/V2024.08.20__feltham_configuration.sql
Hoping to get a basic Feltham configuration through to Preproduction ready for a trial migration ASAP
=> Configure Feltham

src/main/resources/migrations/common/V2024.10.04__wmi_regime_times_post_migration.sql
This will shift the regime times for Wymott to the desired setup POST migration. It should not be merged to dev/pre/prod until after the prod data migration of Wymott data into the system.
=> SAA-2079 Wymott regime times for release post-migration of Wymott data

helm_deploy/values-dev.yaml, src/main/resources/migrations/common/R__v_attendance_creation_data.sql
Set to run tomorrow morning. Disable the check to prevent duplicate attendance records. The experimental test takes care of the
=> SAA-2058: disable existing attendance record check (dev testing)

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/appointment/AppointmentSeries.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/appointment/AppointmentRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ScheduledInstanceController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/appointment/AppointmentController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/appointment/AppointmentService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/AppointmentDetailsIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/AppointmentsIntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/AppointmentControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ScheduledInstanceControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AppointmentServiceTest.kt, src/test/resources/test_data/seed-appointment-attendance.sql
So that a user can mark attendance for multiple appointments
=> SAA-2198: Add endpoint to get multiple appointments

helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml
=> SAA-2223 data fix unemployed by choice AM

helm_deploy/values-prod.yaml
=> SAA-2223 data fix SNI LTSick

renovate.json
=> add rajaram to renovate.json

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivitySchedule.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Allocation.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/AllocationRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/DailyActivityMetricsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityScheduleIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ManageAttendanceRecordsJobIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/PaidToUnpaidFixIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/DailyActivityMetricsServiceTest.kt
Remove eager loading from:
- allocations in activity schedule
- exclusions in allocation
=> SAA-2387: Change exclusions and allocations to lazy loading

applicationinsights.json, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/InboundEventsListener.kt
Update SQS config to recommendations [here](https://github.com/ministryofjustice/hmpps-spring-boot-sqs/blob/main/release-notes/5.x.md#510).
=> Update SQS config to latest recommendations

src/main/resources/application.yml
Reverts ministryofjustice/hmpps-activities-management-api#1568
=> Revert "SAA-2420: Resolve flyway migration issue in preprod"

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/updatesfromexternalsystems/UpdateFromExternalSystemEvent.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/updatesfromexternalsystems/UpdateFromExternalSystemsEventsListener.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/UpdatesFromExternalSystemsEventsIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/updatesfromexternalsystems/UpdateFromExternalSystemEventsListenerTest.kt, src/test/resources/test_data/seed-activity-id-33.sql
Adds a new event listener for `DeallocatePrisonerFromActivitySchedule` events
=> HMAI-629 - Deallocated prisoner from activity event on queue

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivitySchedule.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivitySuitabilityCriteria.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/IntegrationApiController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityScheduleService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/IntegrationApiIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/IntegrationApiControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityScheduleServiceTest.kt
Add GET /activities/schedule/{scheduleId}/suitability-criteria to the Integration-API-Controller
=> HMAI-693 Add GET /activities/schedule/{scheduleId}/suitability-criteria
