ministryofjustice/hmpps-activities-management-api

helm_deploy/hmpps-activities-management-api/values.yaml
Secret name was wrong from the template rename. This corrects it.
=> SAA-33: Correction to cert secret name

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Activity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityCategory.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityEligibility.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityInstance.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityPay.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityPayBand.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityPrisoner.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivitySession.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityTier.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityWaitlist.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Attendance.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AttendanceReason.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/DailyStatistics.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/EligibilityRule.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/EventConsumed.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/PrisonerHistory.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/RolloutPrison.kt, src/main/resources/migration/common/V1__baseline.sql
The changes contain:
- Renaming some of the tables in the DDL script to be inline with an updated data model.
- An initial first cut of mapping JPA entities to the existing baseline Flyway DB migration.
The entities and DB structure are subject to further changes as we learn more during our initial MVP work.
**IMPORTANT:**
**The baseline DDL has changed, the existing DB in development will need dropping or the Flyway migration process will cause the deployment to fail.**
=> SAA-19 preliminary mapping of the JPA entities to the baseline DDL script.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/Activity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivityCategory.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivityEligibility.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivityInstance.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivityPay.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivityPayBand.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivityPrisoner.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivitySession.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivityTier.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/EligibilityRule.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/TransformFunctions.kt
This is the initial work in progress commit to begin process of transforming a persisted activity into it's external API equivalent.
The model objects as they stand lack Swagger documentation.  This will be added in due course.
=> SAA-60 (WIP) initial changes to support transformation of activity entity into the external API equivalents

.circleci/config.yml
Small change the Circle CI configuration to send alerts to the teams dedicated alerts channel.
=> SAA-71 send pipeline alerts to our own dedicated team alerts channel.

README.md
Adding badges for code coverage and build status to the repo readme
=> SAA-70 add code coverage and ci build status badges to the project repo readme.md.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Attendance.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/Attendance.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/AttendanceReason.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/request/AttendanceUpdateRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/AttendanceReasonRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/AttendanceRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/AttendanceController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AttendancesService.kt, src/main/resources/migration/data/R__1_4__attendance_reasons.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/AttendanceIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/AttendanceControllerTest.kt, src/test/resources/test_data/seed-reference-data.sql
This is a first cut of batch marking of attendance records.
This is taking a very thin slice in terms of what is actually updated, in this case it is purely updating the attendance reason for a pre-generated attendance record (note attendance records are not yet pre-generated).
There is no validation taking place as part of this PR e.g. unknown attendance reason codes, attendance record not found etc.
=> SAA-129 initial commit for batch marking of attendance records.

.trivyignore, build.gradle.kts
Update dps-gradle-spring-boot version to 4.5.5 which gives us a trivyignore on the commons-text vulnerability as it cant be updated because its bundled with application insights
See - https://github.com/ministryofjustice/dps-gradle-spring-boot/blob/b0a2008a0606a657ca5774fc3b913503fd009056/release-notes/4.5.5.md
=> SAA-126 Security update - API

helm_deploy/hmpps-activities-management-api/templates/create-activity-sessions-cronjob.yaml
Just a simple cronjob config - just gets the health of the service for now. Will later be changed to trigger processing
=> SAA-135: Create simple cronjob config

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/config/ControllerAdvice.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityScheduleInstanceController.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityScheduleInstanceControllerTest.kt
Validate the following
- Incorrect date formats - example error - Error converting 'endDate' (01/10/2022): Failed to convert value of type 'java.lang.String' to required type 'java.time.LocalDate'
- Exceeding 3 month date range limit - Validation failure: Date range cannot exceed 3 months
- Missing start date param - Required request parameter 'startDate' for method parameter type LocalDate is not present
- Missing end date param - Required request parameter 'endDate' for method parameter type LocalDate is not present
Changes
- Make controller advice extend ResponseEntityExceptionHandler and override handlerExceptionInternal
- New controller advice function - handleMethodArgumentTypeMismatchException
- Validate date range
=> SAA-156 Add validation to API Endpoint: (prisoner scheduled instances)

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/ScheduledInstanceRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityScheduleInstanceController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledInstanceService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityScheduleInstanceIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityScheduleInstanceControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledInstanceServiceTest.kt
Refinement of api for activity schedule instances - prisoner number becomes optional request param
this allows us to select all the activity scheduled instances for a prison or a prisoner
=> SAA-157 API Endpoint: activity schedule instances

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/AttendanceRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/ScheduledInstanceRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AttendancesService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AttendancesServiceTest.kt
Adding simple implementation for attendance creation in the service layer for the scheduled cron job to use.  There are business rules missing for the first iteration e.g. not checking for suspensions, inactive allocations and not applying pay rates.
=> SAA-176 add minimal attendance creation to the attendance service for the upcoming cron job.

helm_deploy/hmpps-activities-management-api/templates/create-attedance-records-cronjob.yaml
Addition of k8's cronjob for the create daily attendance records.  I have applied this locally to dev and test it.
I have run it several times to ensure it works if is run more than once.
=> SAA-176 adding cronjob for creation of attendance records.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/client/prisonapi/api/PrisonApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/client/prisonapi/model/Alert.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/client/prisonapi/model/Assessment.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ScheduledEventController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledEventService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/client/prisonapi/api/PrisonApiClientTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/wiremock/PrisonApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledEventServiceTest.kt
Corrected prison api request param names
prison api Alert and Assessment data coming through with null offender numbers from dev - made property nullable. Throw 404 if prison code and prisoner number don't match query params 
Swagger endpoint docs fix
=> SAA-160 API endpoint to get scheduled events (combined) BUGFIX

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/EventType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/PrisonRegimeService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/PrisonRegimeServiceTest.kt
This is just an initial attempt at getting a stubbed service in place to aid with the prioritisation events i.e. activities, appointments, prison visits, adjudication hearings and court hearings.
=> SAA-198 initial commit to get stubbed service in place for event priorities.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/EventPriority.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/EventPriorityRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/PrisonRegimeService.kt, src/main/resources/migration/common/V1__baseline.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/PrisonRegimeServiceTest.kt
**DO NOT MERGE, CONTAINS DB CHANGE**
This change introduces the concept of event priorities for prisons in the domain i.e. when an event takes priority over another should there be a clash because they are both at the same time.
If no priorities exist for a prison then sensible defaults are provided.
=> SAA-198 adding the domain model and DB DDL for event priorities.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/EventCategory.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/EventPriority.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/PrisonRegimeService.kt, src/main/resources/migration/common/V1__baseline.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/PrisonRegimeServiceTest.kt
**DO NOT MERGE.  CONTAINS BREAKING DB CHANGE.**
Introducing another level for event prioritisation.
An event priority can also have an event category e.g. activities can be broken down further into categories education, gym sports fitness, induction, industries, interventions, leisure social and services.
=> SAA-198 adding event category to event priority to allow  for a finer level of prioritisation.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityScheduleController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/PrisonController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityScheduleService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctions.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityScheduleIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/PrisonIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityScheduleControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/PrisonControllerTest.kt
Needed an endpoint to be able to retrieve an activity schedule as part of the allocation journey.
This meant moving an endpoint to another controller as this highlighted an ambiguity in the activity schedule controller.
The UI needs to be updated as a result of this change.
=> SAA-211 new endpoint to retrieve an activity schedule by its idenitfier and moving one out to the prison controller due to a clash.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Allocation.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/Allocation.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/response/PrisonerAllocations.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/AllocationRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/PrisonerAllocationController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AllocationsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctions.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/PrisonerAllocationIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/PrisonerAllocationControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AllocationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctionsTest.kt, src/test/resources/test_data/seed-activity-id-6.sql
As part of this change it decorates the Allocation model to include the activity summary and schedule description to reduce API calls and the need to keep passing them around.
=> SAA-237 new endpoint to retrieve all or only active allocations for prisoners at a given prison.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/client/prisonapi/api/PrisonApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityScheduleService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/client/prisonapi/api/PrisonApiClientTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityScheduleIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/wiremock/PrisonApiMockServer.kt
There is a problem calling the full prisoner info details on the prison api endpoint (in dev) when some of the data is missing on offender records in our service.  Allocations does not need the full prison info anyway and this change works around this for now.  Further investigation is needed to see if this is a genuine problem or simply bad data in DEV.
=> SAA-247 changing the call to prisoner api for allocations to not use full info call as this is not needed.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/client/prisonapi/model/Alert.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/client/prisonapi/model/Assessment.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/client/prisonapi/model/PrisonApiTypesTest.kt
There is a risk here if we were to generate the DTO's for prison API again say due to a new endpoint these changes may be overwritten.
The offending endpoint : `/api/bookings/offenderNo/{prisonerNumber}?fullInfo=true`
**_Note: there may be more, these are the two I am aware of._**
=> SAA-247 have identified two attributes returned by prison api can actually be null/empty. This does not align with the API's docs.

README.md, docker-compose.yml, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityPay.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityScheduleService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/EventsPublisher.kt, src/main/resources/application-local.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityServiceTest.kt
We need to save and flush data to ensure timing of data being persisted and event being intercepted are in sync.
**Still to do:**
Integration test (this requires test containers for localstack and updating the CI config to pull in a localstack container).
=> SAA-261 publishing activity creation event and start introduction of localstock for working/testing queues locally.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/config/OpenApiConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityScheduleController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/AttendanceController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityScheduleService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AttendancesService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityScheduleIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/AttendanceIntegrationTest.kt
Protected these endpoints with roles 'ACTIVITY_HUB', 'ACTIVITY_HUB_LEAD', 'ACTIVITY_ADMIN' (any one) 
- POST /activities/{activityId} – Create an activity 
- POST /schedules/{scheduleId}/allocations – Allocate offender to schedule
Protected this endpoint with the 'ACTIVITY_ADMIN' role 
- PUT /attendances – Updates attendance records
=> SAA-281 Roles

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Activity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/Activity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivityLite.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/request/ActivityCreateRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctions.kt, src/main/resources/migration/common/V1__baseline.sql, src/main/resources/migration/data/R__2_1__activities.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityScheduleTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/PrisonIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/PrisonControllerTest.kt, src/test/resources/__files/activity/activity-create-request-2.json, src/test/resources/__files/activity/activity-entity-1.json, src/test/resources/__files/activity/activity-entity-2.json, src/test/resources/test_data/seed-activity-id-1.sql, src/test/resources/test_data/seed-activity-id-2.sql, src/test/resources/test_data/seed-activity-id-3.sql, src/test/resources/test_data/seed-activity-id-4.sql, src/test/resources/test_data/seed-activity-id-5.sql, src/test/resources/test_data/seed-activity-id-6.sql, src/test/resources/test_data/seed-activity-id-7.sql, src/test/resources/test_data/seed-activity-id-8.sql
New Activity property payPerSession. An enum 'H' Half day or 'F' Full day - indicating whether activity payment is for a full day or half day. DB / Entity / Model updates with test data.
=> SAA-288 pay_per_session

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivitySchedule.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityScheduleController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityScheduleService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityScheduleTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityScheduleIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityScheduleControllerTest.kt
I missed this when I did the create allocations work and it was on my TODO/tidy up list, so here it is.
=> SAA-293 recording the (missing) pricinal name against allocation creations.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivitySchedule.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivitySchedule.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivityScheduleLite.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctions.kt, src/main/resources/migration/common/V1__baseline.sql, src/main/resources/migration/data/R__2_2__schedules.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityScheduleTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/ActivityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledInstanceFixture.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctionsTest.kt, src/test/resources/test_data/seed-activity-id-1.sql, src/test/resources/test_data/seed-activity-id-2.sql, src/test/resources/test_data/seed-activity-id-3.sql, src/test/resources/test_data/seed-activity-id-4.sql, src/test/resources/test_data/seed-activity-id-5.sql, src/test/resources/test_data/seed-activity-id-6.sql, src/test/resources/test_data/seed-activity-id-7.sql, src/test/resources/test_data/seed-activity-id-8.sql
Schedules can now have there own start and end dates. These cannot be outside the activity start and end dates.
These new fields have been added to support the ongoing UI work for activity schedule creation.
This will impact the creation of scheduled instances.  This will be addressed separately.
**IMPORTANT: Do not merge without talking to the team, this requires a DB drop.**
=> SAA-303 introduction of start and end dates at the activity schedule level.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Activity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivitySchedule.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityScheduleSuspension.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/CreateActivitySessionsJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityScheduleService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctions.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityScheduleSuspensionTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityScheduleTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ScheduledInstanceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/ActivityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/CreateAttendanceRecordsJobIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/CreateActivitySessionsJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ScheduledInstanceControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AttendancesServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctionsTest.kt
Initial changes to include the start and end dates of a schedule when creating instances of a schedule.
Includes adding some extra validation on the entities themselves around dates and also adding missing unit tests for pulling out schedules from activities for scheduling.
=> SAA-320 initial commit for scheduled instance job to use start and end dates of the schedule as well as the activity.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/EventsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/OutboundEventsServiceTest.kt
The ADR for message formats related to this change can be found in Confluence.
=> SAA-352 bring the outbound domain even message inline with the ADR, requires AdditionalInfo object as part of message.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Allocation.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/AllocationController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AllocationsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctions.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/ActivityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/AllocationIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/AllocationControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AllocationServiceTest.kt
On the back of the data sync work back to NOMIS we need support the retrieval of prisoner allocations by it's id for the mapping service to use.
=> SAA-353 adding new endpoint to support the retrieval of allocations by id.

README.md, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Allocation.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/PrisonPayBand.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/Allocation.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/AllocationIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/PrisonerAllocationIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/testdata/IntegrationTestPayBands.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctionsTest.kt
Expose the full pay bands over the API instead of just the ID. 
I've added the Pay Bands used by the integration tests into a single file as they need to match those in the DB seed file and, should that seed file change, the corresponding Pay Band expectations need only be changed in one place (as opposed to being scattered across the tests)
=> SAA-357. Expose the full pay bands instead of just the ID

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/client/prisonapi/model/CaseLoad.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/request/AppointmentCreateRequest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/request/AppointmentCreateRequestTest.kt
Prevents the creation of appointments where the start date and time are in the past. Previously the code would allow same day appointments that started earlier than the current time.
=> SAA-348: Date and time should not be in the past

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivitySchedule.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Allocation.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityScheduleService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AllocationsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AttendancesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/CapacityService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityScheduleTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AllocationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/CreateAttendanceRecordsJobIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityScheduleServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AttendancesServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/CapacityServiceTest.kt, src/test/resources/test_data/seed-activity-id-1.sql, src/test/resources/test_data/seed-activity-id-4.sql, src/test/resources/test_data/seed-activity-id-6.sql
Changes to attendance record creation and capacity calculations on the back of introducing a status field to allocations.
Having a status field on allocations removes the need to check the dates on them.
The status field will be managed going forwards to determine an allocations status.
=> SAA-417 ensure both attendance creation and capacities take deallocated offenders into account.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Allocation.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Attendance.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ScheduledInstance.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivityScheduleInstance.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/request/ScheduleInstanceCancelRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/AttendanceReasonRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ScheduledInstanceController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledInstanceService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AttendanceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ScheduledInstanceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/ActivityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityScheduleInstanceIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivityScheduleInstanceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/AttendanceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ScheduledInstanceControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AttendancesServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/PrisonerSearchPrisonerFixture.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledInstanceServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctionsTest.kt, src/test/resources/test_data/seed-activity-id-16.sql
Adds cancel scheduled instance endpoint, `/scheduled-instances/{instanceId}/cancel`
Calling this endpoint will cancel the schedule instance, and update the status and pay of any associated attendance records.
=> SAA-420: Cancel schedule instance

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/client/prisonapi/api/PrisonApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/client/prisonersearchapi/api/PrisonerSearchApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ScheduledEventController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledEventService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctions.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/client/prisonapi/api/PrisonApiClientTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ScheduledEventControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledEventServiceTest.kt
This PR:
* Replaces the Mono.zip and Mono<List<T>> return types from prison API with Kotlin coroutines and Deferred<List<T>>
* It uses runBlocking {} enclosures, suspend functions and async {} calls for visits, activities, transfers, and court hearings.
* Removes the confusing, multi-layered transform functions for scheduled events - much clearer (I think).
* Allows (as a next step) the individual transform of court hearings, activities, appointments, visits and transfers when needed.
* We already know that we want to treat these events differently, show different detail, so this will be required.
* Updates all affected tests.
=> SAA-490 get scheduled events in parallel using Kotlin coroutines

build.gradle.kts
Version 2.0.3 contains a breaking change that reverses the default of the required flag for non-nullable fields from true to false. This means we'd need to add `required = true` to all non-nullable fields with a @Schema annotation - which is a lot of work and seems completely wrong to me. So I'm trying to get springdoc to reverse this breaking change, but in the meantime we need to stick to v2.0.2 so that all non-nullable fields are required.
=> SDIT-423 Stick to springdoc version 2.0.2

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/config/FeatureSwitches.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/EventsPublisher.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/EventsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/config/FeatureSwitchesTest.kt
The upshot of this PR will hopefully mean we can add the code for raising events prior to them be used outside of our service.
If events are raised and published but not consumed then alerts can/will be raised on the DPS alerts channel.
=> SAA-554 initial commit to introduce finer grained feature switching, particularly around sending and receiving events.

helm_deploy/hmpps-activities-management-api/templates/manage-allocations-cronjob.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/ManageAllocationsJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/JobTriggerController.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ManageAllocationsJobIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/ManageAllocationsJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/JobTriggerControllerTest.kt
There are some extra tasks around changing the status of allocations that we can piggy back off the existing deallocation job hence the renaming to be managing allocations.
This helps prevent conflicts with regards to CRON timings as well.  All changes to the allocations will capture in job.
=> SAA-422 small refactoring exercise to consolodate the allocations job. This is going to be extended to include additional tasks in upcoming work.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/client/prisonapi/api/PrisonApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/client/prisonapi/overrides/Education.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/response/ActivityCandidate.kt
Small fix for generated prison API types being different to expected nullable fields for Education.
=> SAA-606: Override the Education class to fix nullable fields.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Attendance.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AttendancesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctions.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AttendanceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AttendancesServiceTest.kt
Enables `otherAbsenceReason` field to be set when marking attendance
=> SAA-654: Record other absence reason

helm_deploy/hmpps-activities-management-api/values.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/CreateScheduledInstancesJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AttendancesService.kt
This is to align our service with others who subscribe or generate events on the HMPPS domain events SNS topic.
A change went into Cloud Platform to automate the generation of consistently named secrets - our service is in this list - so this change makes our API service use the consistent secret name.
A further cloud platform PR will be raised to remove the old secret being created.
=> SAA-606: Update secret name for hmpps domain events SNS topic values.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivitySchedule.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Allocation.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/Allocation.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityScheduleService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AppointmentService.kt, src/main/resources/migrations/common/V2023.05.11__booking_id_mandatory_on_allocation.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/PrisonerAllocationIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/AllocationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctionsTest.kt, src/test/resources/test_data/seed-activity-id-6.sql
This is part one of two PR's.  Will most likely need to regenerate the types for the UI.
Ready to be reviewed but please do not merge.
=> SAA-701 exposing the suspension details on allocations as currently not visible when pull back allocations.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/InboundEventsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/EventHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/InterestingEventHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/OffenderReceivedEventHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/OffenderReleasedEventHandler.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/InboundEventsServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/InterestingEventHandlerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/OffenderReceivedEventHandlerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/OffenderReleasedEventHandlerTest.kt
This change allows for a more fluent api approach when an event handler is called/used.
=> SAA-529 refactoring handlers so they return an Outcome instead of a boolean.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Attendance.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AttendanceTest.kt
Fixes bug causing `otherAbsenceReason` to be recorded as null in attendance history
=> SAA-654: Bug fix + test

helm_deploy/values-preprod.yaml
Preprod API pods failing to start with an AppInsights configuration error.
Logs indicate it may be to do with sampling that was configured for prod and preprod, so reverting to no sampling for preprod (like it is in dev).
This may not work, but it won't harm. The other possibility is that our spring profiles are not set correctly when running in preprod.
=> SAA-609: App insights logging fix for preprod

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Allocation.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ManageAllocationsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/ActivitiesChangedEventHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/OffenderReleasedEventHandler.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AllocationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/AllocationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityScheduleServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/CapacityServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ManageAttendancesServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/ActivitiesChangedEventHandlerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/OffenderReceivedEventHandlerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/OffenderReleasedEventHandlerTest.kt
Updates to ensure deallocation job factors in planned deallocations in the job which deallocates and ends allocations that have an end date (or planned end date).
=> SAA-763 planned allocation deallocations should be considered when the deallocation job runs.

README.md, generate-prison-api-types.sh, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Allocation.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/request/PrisonerDeallocationRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityScheduleService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityScheduleIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/AllocationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityScheduleControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/AllocationControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityScheduleServiceTest.kt
Some of the deallocation reason codes are only applicable to the API e.g. when jobs run.
=> SAA-780 the reason codes presented to the UI need to be restricted to a subset of codes.

helm_deploy/hmpps-activities-management-api/templates/manage-allocations-activiate-cronjob.yaml, helm_deploy/hmpps-activities-management-api/templates/manage-allocations-deallocate-cronjob.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Allocation.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/ManageAllocationsJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/JobTriggerController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ManageAllocationsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AllocationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ManageAllocationsJobIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/ManageAllocationsJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/JobTriggerControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ManageAllocationsServiceTest.kt, src/test/resources/test_data/seed-allocations-pending.sql
Previously the timing for activating pending allocations for today would have been performed at 10pm.
Now they will be activated at 2am in time for other jobs to do what is needed for the day e.g. create attendance records for active allocations.
=> SAA-820 changes to allow allocation management operations to be run and different times.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Job.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/CreateScheduledInstancesJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/ManageAllocationsJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/ManageAttendanceRecordsJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/SafeJobRunner.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/JobRepository.kt, src/main/resources/migrations/common/V2023.06.13__add_job.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/JobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/CreateScheduledInstancesJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/ManageAllocationsJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/ManageAttendanceRecordsJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/SafeJobRunnerTest.kt
These changes do not guarantee jobs from failing but it does mean any jobs that run in the same call will get the opportunity to run should a previous one fail.  It also records the success/failure of the job in the DB.
This can be expanded on - thoughts are to provide some information to the Job entity that gets created with some details of the job outcome.
=> SAA-839 work to improve resilience of our jobs and record their success or failure in the DB should we need to recover/re-run.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Attendance.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AttendanceTest.kt
Alongside the unit tests I have also performed the following manual test
- Create an activity via the UI with a start date of today
- Allocate three prisoners to that activity
- Set the status of one of the prisoners to SUSPENDED.
- Generate the attendance records using swagger (one of them now has an attendance reason of 7 - SUSPENDED)
- Cancel the session. The attendance records for the unsuspended prisoners have their reason set to 8 - WAITING. The attendance record for the suspended prisoner still has its attendance reason set to 7 and the prisoner attendance and pay is recorded as **SUSPENDED NO PAY**
- Uncancel the session. The attendance records for the unsuspended prisoners have their reason set to null. The attendance record for the suspended prisoner still has its attendance …
=> SAA-773 - Do not overwrite status of suspended prisoners on cancel/uncancel

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Allocation.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ManageAllocationsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/ActivitiesChangedEventHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/OffenderReleasedEventHandler.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityScheduleTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AllocationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/AllocationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityScheduleServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ManageAllocationsServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ManageAttendancesServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/ActivitiesChangedEventHandlerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/OffenderReceivedEventHandlerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/OffenderReleasedEventHandlerTest.kt
Although allocations due to end are being picked up by the job to end them if there was a planned deallocation present which applied to the day of ending it was not being used.  This fix resolves that.
=> SAA-851 changes to fix issue where planned deallocation not being used if present upon ending allocations.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/client/prisonapi/api/PrisonApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/client/prisonapi/overrides/OffenderNonAssociation.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/client/prisonapi/overrides/OffenderNonAssociationDetail.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/client/prisonapi/overrides/OffenderNonAssociationDetails.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/suitability/NonAssociationSuitability.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/suitability/nonassociation/NonAssociationDetails.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/suitability/nonassociation/OffenderNonAssociation.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/CandidatesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctions.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/client/prisonapi/api/PrisonApiClientTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/CandidatesServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctionsTest.kt
This adds overrides for fields `assignedLivingUnitDescription` and `assignedLivingUnitId` of `OffenderNonAssociation`.
Needed since these fields can be null despite being required.
=> SAA-669: Added overrides

src/main/resources/migrations/common/V2023.06.20__fix_attendance_sync_view.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/AttendanceSyncIntegrationTest.kt, src/test/resources/test_data/seed-activity-id-17.sql
And only grab the active allocation (i.e. not ENDED)
=> SDIT-897 Cater for multiple allocations on attendance sync

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivitySchedule.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityScheduleSlot.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/request/ActivityCreateRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/request/ActivityUpdateRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityScheduleSlotTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityScheduleTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityIntegrationTest.kt, src/test/resources/test_data/seed-activity-update-slot.sql
This is the first of two PR's.  It focuses on changing the way we update slots.
Previously it would clear all slots and re-add them again.
The changes in this PR means we only clear out slots we no longer care about and update those that we do care about.
=> SAA-876 reworking updates to slots to update slots affected and remove those no longer needed instead of removing all and then re-adding.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivitySchedule.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ScheduledInstance.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityScheduleTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityIntegrationTest.kt
I have run this locally against the UI.
If the slots are updated via the slots change/link screen upon editing an activity changes to slots and instances are propagated.
=> SAA-868 updates to activity schedule slots is now also applied to instances.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivitySchedule.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Allocation.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityScheduleTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AllocationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityIntegrationTest.kt, src/test/resources/test_data/seed-activity-update-end-date.sql
I have tested these changes locally running the UI against them.
=> SAA-875 apply activity end date changes to the associated schedules, allocations and planned deallocations.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/LocationController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/LocationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/LocationIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/LocationControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/LocationServiceTest.kt
Matches the existing Whereabouts approach used in https://github.com/ministryofjustice/whereabouts-api/blob/main/src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/LocationGroupServiceSelector.kt and https://github.com/ministryofjustice/whereabouts-api/blob/main/src/main/java/uk/gov/justice/digital/hmpps/whereabouts/services/LocationGroupFromPrisonApiService.kt
Tested with Leeds and Gartree
=> SAA-918: Use default location prefix format where no explicit pattern exists

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Allocation.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AllocationTest.kt
This resolves a gap in the update activity end date process whereby and allocation end date can end up before the allocation start date.
=> SAA-875 small change to ensure when an acitivity end date is change we cannot end up with an allocation end before the start.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Activity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivitySchedule.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityScheduleTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AllocationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/ActivityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityServiceTest.kt
The following (new) checks have been added:
- You cannot change the activity start date to be after its end date.
- You cannot change the activity start date if it has already has started i.e. today or earlier.
- You cannot change the activity start date to the today's date, it must be a future date.
- You cannot change the activity start date to be later than that of any allocations.
=> SAA-875 futher changes to ensure date boundaries are honoured when changing activity start and end dates.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityServiceTest.kt
The API was not guarding the updating of archived activities.
At time of writing the frontend still doesn't.  You can go directly to edit an (archived) activity bypassing the journey to get there.
=> SAA-877 archived activities should not be updateable this change prevents that.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/ActivityRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityServiceTest.kt
This change fixes an issue whereby even though we are supplying the prison code along with the activity prior to update we were not checking the activity is at the given prison code.
=> SAA-877 checking the supplied prison code matches that of the activity prior to updating.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Appointment.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AppointmentOccurrence.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AppointmentOccurrenceSearch.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/BulkAppointment.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/AppointmentDetails.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/AppointmentOccurrenceDetails.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/BulkAppointmentDetails.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/response/AppointmentOccurrenceSearchResult.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/PrisonApiTransformations.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctions.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AppointmentOccurrenceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AppointmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/BulkAppointmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/AppointmentEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/AppointmentModelFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/AppointmentDetailsIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/AppointmentOccurrenceDetailsIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/BulkAppointmentDetailsIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ScheduledEventIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AppointmentDetailsServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctionsTest.kt
Updates endpoints returning appointment details to include appointment name.
=> SAA-909: Return appointment name in API responses

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/AllocationRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AllocationsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AllocationServiceTest.kt
This change fixes an issue whereby even though we are supplying the prison code along with the allocation prior to update we were not checking the allocations activity is at the given prison code.
=> SAA-877 checking the supplied prison code matches that of the allocation prior to updating.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityScheduleService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AllocationsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/ActivityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityScheduleServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AllocationServiceTest.kt
Changes to ensure allocation start date changes are always in the future.
We cannot create/update an allocations start date to today's date.
=> SAA-954 allocation start date must be in future on creation and updates.

helm_deploy/hmpps-activities-management-api/values.yaml
Part of the Cloud Platform push to remove long-lived credentials.
=> SAA-803: Added IRSA service account and removing access keys for queues and topics

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Attendance.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/AttendanceRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/ActivitiesChangedEventHandler.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AttendanceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/InboundEventsIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/ActivitiesChangedEventHandlerTest.kt, src/test/resources/test_data/seed-activity-changed-event.sql
When an allocation is suspended any future attendance records associated with that allocation should also be suspended without pay.
In this scenario future attendance records are any attendance records that are after the time of the allocation being suspended.
=> SAA-987 changes to suspend future attendances when allocations are suspended via the acitivities changed event.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivitySchedule.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityScheduleTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityIntegrationTest.kt
Small change to the create / remove instance logic. This fixes the bug where all past instances are removed during a slot update and implements the following rules for activity create / edit requests:
- All past instances should be kept (regardless of attendance or previous slot settings)
- Any instances already scheduled for today should remain active
- Any future instances (tomorrow or after) which are no longer valid should be removed (regardless of existing attendance records)
- Any future instances (tomorrow or after) which are still valid should be kept
- Where new instances need to be created these should be created for tomorrow onwards
=> SAA-1012: Only remove redundant future instances when updating slots

src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityServiceTest.kt
Temp PR - until fix comes - to comment a failing test. 
Required to test deployment of API service into new namespace.
=> SAA-853: Comment a failing test.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ScheduledInstance.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/AttendanceRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/ActivitiesChangedEventHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/OffenderReceivedEventHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/OffenderReleasedEventHandler.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ScheduledInstanceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/InboundEventsIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/OffenderReleasedEventHandlerTest.kt, src/test/resources/test_data/seed-offender-released-event-deletes-attendances.sql
This is the first of two changes.  This change is to allow for the removal of futures upon a prisoner being permanently released from prison.
Part two is to create an audit trail with the DPS audit service.
=> SAA-1016 changes to support removal of attendances on reciept of a prisoner being released event.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivitySchedule.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/PrisonRegimeService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityScheduleTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/ActivityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ManageScheduledInstancesServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/PrisonRegimeServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctionsTest.kt
This change primarily updates the `addSlot()` method to support adding slots for multi-week schedules, but also includes some improves around creating and removing instances.
Note: Because `createActivity()` and `updateActivity()` use the request models I will add tests for creating and updating multi-week schedules once those models have been updated.
=> SAA-996: Multi-week schedule updates

src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityServiceTest.kt
Fixes flaky test caused by slot day falling out of week bounds during on weekends
=> SAA-849: Fix flaky test

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityScheduleController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/AllocationController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/AppointmentController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/AppointmentDetailsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/AppointmentInstanceController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/AppointmentOccurrenceController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/AppointmentOccurrenceDetailsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/BulkAppointmentController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/BulkAppointmentDetailsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/CaseloadHeader.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ScheduledInstanceController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/WaitingListApplicationController.kt
As part of this fix I have pulled the caseload header parameter out into its own annotation to save repetition/duplication.
Example before:
Example after (note `string` now showing under caseload-id):
=> SAA-1086 changes to fix API spec generation with the caseload header when using the Open API gen tool.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Allocation.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AuditableEntityListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/WaitingList.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/audit/AuditableEvent.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/audit/PrisonerAllocatedEvent.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityScheduleService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/AuditTransformations.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AuditableEntityListenerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/WaitingListTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/ActivityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/audit/PrisonerAllocatedEventTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityScheduleServiceTest.kt
This change moves away from using the audit event listener. The main reason being it is getting too difficult to determine the nature of the audit event.
Note: there is no integration test change here as part of this PR, the events raised stays the same the prisoner allocated event.
=> SAA-1081 auditing the associated waiting list identifier with the prisoner allocated audit event if there is one.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/WaitingList.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/WaitingListRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/WaitingListService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/WaitingListTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/ActivityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityScheduleServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/CandidatesServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/WaitingListServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/AuditTransformationsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctionsTest.kt
Providing a reusable service layer function to decline PENDING and/or APPROVED waiting list applications.
This will be used by background jobs e.g. activities ending jobs and event handlers e.g. prisoner release event.
=> SAA-1030 intial commit for supporting declining waiting lists.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AttendanceSync.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/AttendanceSyncRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/SynchronisationService.kt, src/main/resources/migrations/common/V2023.08.22__fix_attendance_sync_view.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/AttendanceSyncIntegrationTest.kt, src/test/resources/test_data/seed-activity-id-17.sql
Fixes a problem with attendance sync. that we were experiencing in dev - an offender that was allocated, released, returned to prison on a new booking and reallocated to the same activity always failed attendance sync. because we tried to attend against the old allocation. (A4744DZ).
=> SDIT-1039 Workaround Hibernate bug which returned duplicate records

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/MigrateActivityService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/MigrateActivityServiceTest.kt
For migrated activities.
This keeps them consistent with other activities and prevents an odd description showing on forms that use this field.
=> SAA-1142: Keep description and summary the same.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Appointment.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AppointmentOccurrence.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AppointmentOccurrenceEntityListener.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AppointmentOccurrenceUpdateDomainService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/request/AppointmentOccurrenceUpdateRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AppointmentOccurrenceService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/telemetry/TelemetryTransformFunctions.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AppointmentOccurrenceEntityListenerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AppointmentOccurrenceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AppointmentOccurrenceUpdateDomainServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AppointmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/AppointmentEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/AppointmentOccurrenceIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/InboundEventsIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/request/AppointmentOccurrenceUpdateRequestTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AppointmentOccurrenceServiceCancelTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AppointmentOccurrenceServiceUpdateTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/telemetry/AppointmentOccurrenceTelemetryTransformFunctionsTest.kt
SAA-1055 requires all operations on very large group appointments, those represented by more than 500 instances in NOMIS, to follow a partial async pattern. The requested operation is applied synchronously to the first occurrence in the appointment and the remaining occurrence operations are actioned asynchronously.
This proved to be challenging for updating appointments without significant code duplication. In order to prevent this, the existing occurrence service was refactored and split into a smaller service responsible for validating and coordinating the update along with a domain service containing the business logic to action the update. This pattern supports reusing the domain service in an asynchronous job.
As part of this refactor, the approach to publishing the sync events was …
=> SAA-1055: Refactor update appointment towards DDD

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/MigrateActivityService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/MigrateActivityServiceTest.kt
For now, because Risley use only levels BAS, STD and ENH, this means we will filter pay rates that contain any other incentive levels. For example, EN2 or ENT rates will be discarded in the migration.
=> SAA-1061: Filters any pay rates which contain incentive levels not in our "common" list.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ManageScheduledInstancesService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ManageScheduledInstancesServiceTest.kt
Problem: The createScheduledInstances job was running as a single, long transaction, and immediately after a prison migration this is potentially a long job.  It was creating sync events and the sync service was detecting them and calling back for data before it had been committed.
This change alters the transaction boundaries such that each activity is treated as its own transaction and committed immediately after raising an event.
It also fixes some issues with the job runner - this job was recorded two job results every time it ran, so this is also now resolved.
=> SAA-1159 split transactions within a potentially long-running job

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctions.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityScheduleInstanceIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctionsTest.kt
Updates Attendance entity transformer to add support for `editable` flag.
=> SAA-1187: Fixes editable flag bug

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/WaitingList.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/WaitingListApplication.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctions.kt, src/main/resources/migrations/common/V2023.09.15__add_waiting_list_status_updated_column.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/WaitingListServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctionsTest.kt
Adds new field to `waiting_list` to record status updates independently of other changes.
"Last changed" text should only update when the status itself has been updated:
=> SAA-1194: Added status update timestamp

src/main/resources/migrations/common/V2023.09.19__update_risley_pay_bands.sql
This changes Risley's pay bands from Low, Medium, High to the default 1-10 used by NOMIS in all emvironments.
(similar to how LEI is setup in our service).
It also updates any Activities and Allocations as part of the migration.
=> SAA-204 update risley pay bands

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/client/prisonapi/api/PrisonApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/InternalLocationEvents.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/InternalLocationEventsSummary.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/AppointmentInstanceRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/PrisonerScheduledActivityRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/LocationController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ScheduledEventController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/InternalLocationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledEventService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/client/prisonapi/api/PrisonApiClientTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AppointmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/ActivityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/AppointmentEntityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/LocationFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/PrisonApiFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/LocationIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ScheduledEventIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/wiremock/PrisonApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/LocationControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ScheduledEventControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/InternalLocationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledInstanceServiceTest.kt
Adds two new endpoints to support movement lists:
- /locations/prison/{prisonCode}/events-summaries - Get a list of internal locations that have events scheduled to take place on the specified date and optional time slot
- /scheduled-events/prison/{prisonCode}/locations - Get a list of scheduled events for a prison and list of internal location ids numbers for a date and optional time slot
=> SAA-552: Movement list endpoints

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/ActivitiesChangedEventHandler.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/ActivitiesChangedEventHandlerTest.kt
We (think) we are seeing activities changed events succeeding on retries.
This would suggest there may be a timing issue e.g. seeing the event before the data retrieved prisoner search is updated.
=> SAA-1278 increasing logging for the activities change event as we think there may be timing issues when calling prisoner search.

src/main/resources/whereabouts/patterns/RSI.properties
This was not present in Whereabouts location mappings either, so is either a new set of cells or the wing was not previously using the Whereabouts unlock lists.
=> SAA-1280: Adding a landing 3 to Wing R in the location mapping file.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/client/prisonapi/api/PrisonApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/client/prisonapi/extensions/MovementExt.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/client/prisonersearchapi/extensions/PrisonerExt.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/common/CollectionExt.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Allocation.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/ManageAllocationsJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/AllocationRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ManageAllocationsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/ActivitiesChangedEventHandler.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/client/prisonapi/api/PrisonApiClientTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/client/prisonersearchapi/extensions/PrisonerExtTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AllocationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/Assertions.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/PrisonApiFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/TimeSource.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/InboundEventsIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ManageAllocationsJobIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/wiremock/PrisonApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/wiremock/PrisonerSearchApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/ManageAllocationsJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ManageAllocationsServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/ActivitiesChangedEventHandlerTest.kt, src/test/resources/test_data/seed-allocations-due-to-expire.sql
**DO NOT MERGE**
The jobs for allocation activation and ending now has to consider whether pending allocations should be started/suspend/ended depending on the prisoners active status and/or location in relation to when the allocation was made.  As part of this we also now look at their latest last move based on them being out or their current prison or in at at a different prison.  If they have been out of the prison the allocation was made for more days than is allowed based on the max days out in the prison regime config then the allocation(s) will be ended.
=> SAA-1221 suspension and end of pending allocations need to be considered when starting and ending allocations

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/SafeJobRunner.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ManageAllocationsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ManageAllocationsJobIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/wiremock/PrisonerSearchApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/AppointmentMetricsJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/CancelAppointmentsJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/CreateAppointmentsJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/CreateScheduledInstancesJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/DeleteMigratedAppointmentsJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/ManageAllocationsJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/ManageAppointmentAttendeesJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/ManageAttendanceRecordsJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/SafeJobRunnerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/UpdateAppointmentsJobTest.kt, src/test/resources/test_data/clean-all-data.sql
Errors do not get propagated on safe job execution, as a result we are not seeing DPS alerts when a job fails to execute.
To date this has not been a problem in production.  It was noticed in dev due to external API services we use being disabled out of normal office hours e.g. prison search API is turned off late evening and comes back online at approx 6:20 UTC.
A runtime exception will now be thrown when a job fails to execute cleanly.  Note we still record the failure in the activities DB.
=> SAA-1325 jobs should throw runtime exception on safe job failure to ensure alerts get propagated accordingly.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/SafeJobRunner.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ManageAllocationsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ManageAllocationsJobIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/wiremock/PrisonerSearchApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/AppointmentMetricsJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/CancelAppointmentsJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/CreateAppointmentsJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/CreateScheduledInstancesJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/DeleteMigratedAppointmentsJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/ManageAllocationsJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/ManageAppointmentAttendeesJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/ManageAttendanceRecordsJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/SafeJobRunnerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/UpdateAppointmentsJobTest.kt, src/test/resources/test_data/clean-all-data.sql
Reverts ministryofjustice/hmpps-activities-management-api#645
This did not have the desired impact.  What I failed to realise/consider is the jobs are run asynchronously (facepalm)
=> Revert "SAA-1325 jobs should throw runtime exception on safe job failure to ensure alerts get propagated accordingly."

docker-compose-localstack.yml, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/client/prisonapi/api/PrisonApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/InboundEvents.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/InboundEventsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/InterestingEventHandler.kt, src/main/resources/application-localstack.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/InboundEventsIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/InboundEventsServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/InterestingEventHandlerTest.kt, wiremock-docker/__files/prisoner-search-api/prisoners/G7806VO.json, wiremock-docker/mappings/prison_search_api_get_by_prisoner_number.json
**LOW RISK**
The decision has been made to provide users with the visibility of all release related events for their caseload in the change of circumstances screens in the UI.  The changes in this PR ensure all of the current release events are recorded regardless of whether they succeed or fail so they can then be displayed accordingly.
Example activities change release event as seen in the UI when running locally. Related [PR](https://github.com/ministryofjustice/hmpps-activities-management-api/pull/649)
=> SAA-1334 changes to support the capture of release events whether they succeed or fail as events of interest.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/client/prisonapi/overrides/Movement.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/InterestingEventHandler.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/client/prisonapi/model/PrisonApiTypesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/InterestingEventHandlerTest.kt
Small change CoC for release events.  Would have done this on the original PR bit having issues with github.
We should record the prison id/code from the release event itself and not where the prisoner currently is as this may be different and if it was different it would not show up on the prison they were released from on the CoC UI.
=> SAA-1335 use prison code off event for release events only.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctions.kt
I can provide some context regarding the necessary modification. The user interface, specifically the attendance-details.njk file, relies on the `otherAbsenceReason` property from the `attendance` object. However, during the transformation process from Model to Data classes, this particular value is not being assigned.
Resolution:
I have addressed this issue by initializing the `otherAbsenceReason` field within the `attendance` data class.
Verification:
This change has been thoroughly verified, and existing test cases cover this scenario.
=> SAA-1300 Absent Reason added to attendance

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/InterestingEventHandler.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/InterestingEventHandlerTest.kt
**LOW RISK**
Small tweak to include the release prison code in the event review data when capturing and storing releases for event review presented on the change in circumstances screen in the UI.
=> SAA-1335 capture the released prison code in the stored event data for clarity.

helm_deploy/hmpps-activities-management-api/templates/create-scheduled-instances-cronjob.yaml, helm_deploy/hmpps-activities-management-api/templates/manage-allocations-activate-cronjob.yaml, helm_deploy/hmpps-activities-management-api/templates/manage-allocations-deallocate-cronjob.yaml, helm_deploy/hmpps-activities-management-api/templates/manage-appointment-attendees-cronjob.yaml, helm_deploy/hmpps-activities-management-api/templates/manage-attendance-records-cronjob.yaml, helm_deploy/hmpps-activities-management-api/values.yaml, helm_deploy/values-dev.yaml
**LOW (MEDIUM?) RISK**
Pulled out the job times into env vars in the helm config so we can alter the times at which jobs run for each environment where needed.
The driver for this is due to the fact some core services we use are turned off overnight.  The also means we can remove any jobs which have currently been manually applied to dev as a temporary workaround.
=> SAA-1337 pulled job times out into reusable env vars so can have differenent job times for each environment where needed.

build.gradle.kts
**LOW RISK**
We have been sharing the same root folder for the external API we generate which can cause issues with files being potentially overwritten.
This change ensures each external API we generated has it's own root folder to avoid any clashes.
=> SAA-1341 external generated API's should have their own generation root folder to avoid files being overwritten by other API's generated.

helm_deploy/hmpps-activities-management-api/templates/queue-housekeeping-cronjob.yaml, helm_deploy/hmpps-activities-management-api/values.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/config/ResourceServerConfiguration.kt
At the moment when messages are put onto the DLQ's it requires manual intervention to retry them.  This change automates the retry.
Note: It will still raise an alert if the retry fails.
=> SAA-1345 job to automatically retry messages on DLQ's and reduce the level of manual intervention.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AppointmentCancelDomainService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AppointmentEntityListener.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AppointmentCancelDomainServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AppointmentEntityListenerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/AppointmentIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AppointmentServiceAsyncTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AppointmentServiceCancelTest.kt
Updates appointment cancellation code to wrap transactions in `newSpringTransaction` then publishes sync events after cancellations have been persisted.
=> SAA-1258: Cancel appointment post transaction sync events

build.gradle.kts, helm_deploy/hmpps-activities-management-api/values.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/SafeJobRunner.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/MonitoringService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/AppointmentMetricsJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/CancelAppointmentsJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/CreateAppointmentsJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/CreateScheduledInstancesJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/DeleteMigratedAppointmentsJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/ManageAllocationsJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/ManageAppointmentAttendeesJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/ManageAttendanceRecordsJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/SafeJobRunnerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/UpdateAppointmentsJobTest.kt
This is the first step towards raising visibility of job failures to the team (mainly the dev team initially).
The intention is to raise both Slack and email alerts.  This requires some initial configuration vi [Sentry.IO](https://sentry.io)
I have set up a project and team in Sentry. Team members will need to log into and join to receive email alerts. You can log in with you Github account.
I have added the relevant secret to the k8s dev namespace.  Once that is proven I will adde to the higher environments.
=> SAA-1357 add Sentry integration to capture and raise alerts for all job failures.

README.md, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/SafeJobRunner.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ManageAttendancesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/MonitoringService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/SafeJobRunnerTest.kt
Adding (missed) call to monitoring service in the safe job runner.
=> SAA-1357 add missing call to monitoring service where a subsequent job can fail (not run) due to the first not working.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Allocation.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AllocationTest.kt
Small change to fix a bug where an updated allocation end date is validated against the existing allocation end date.
=> SAA-1383: Fixed allocation end date logic

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivitySchedule.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Allocation.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/Allocation.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/request/PrisonerAllocationRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityScheduleService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityService.kt, src/main/resources/migrations/common/V2023.11.24__pay_band_optional_on_allocation.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AllocationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/ActivityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/AllocationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityScheduleControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityScheduleServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/MigrateActivityServiceTest.kt, src/test/resources/__files/activity/activity-entity-3.json
**MEDIUM RISK**
The is the second part of the API changes for the creation of paid or unpaid activities.  This changes the allocation journey to enforce pay band rules i.e. cannot have a pay band for unpaid activity. Pay band becomes nullable on allocations.
The first PR can be viewed [here](https://github.com/ministryofjustice/hmpps-activities-management-api/pull/697)
Still to do in separate PR's:
- Changes to attendance for unpaid activities.
- Change the update Activity journey to check if paid or unpaid. Can't change if activity has any allocations.
=> SAA-1389 changes for paid and unpaid activities when allocating to an activity.

src/main/resources/migrations/common/V2023.11.29__configure_liverpool_all_envs.sql
This sets up the HMP Liverpool regime config, pay bands and rollout prison data, currently set to rolled out == false for both Activities and Appointments.
=> SAA-1367: Setup Liverpool config data.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AppointmentSeriesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AppointmentService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AppointmentSeriesServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AppointmentServiceTest.kt
[](url)Ensure server-side validation is in place for the 'extra information' field in the VLB appointment process, prior to confirmation.
**Before:**
**After**
=> SAA-1361 VLB Server Side Validation

Dockerfile
=> SAA-1427 temporarily using JDK to aid diagnosing memory usage of the deployed containers.

helm_deploy/hmpps-activities-management-api/values.yaml
This is what DEV would have been at prior to enabling the use of the JAVA_OPTS env var.
The is intentional as this should help highlight slow areas in the API and focus on optimising it where possible.
=> SAA-1427 reducing default heap size to fix OOM errors on PODs. Prod is still at 1024.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/client/prisonapi/api/PrisonApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/OffenderMergedEventHandler.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/InboundEventsIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/OffenderMergedEventHandlerTest.kt
Switching to use prison API for looking up merged offender details instead of prisoner search API.
In the time we have received a prisoner merge event and attempted to process it (which in turn looks up the prisoner details via an external API call) it looks like the prisoner changes have not yet been indexed in prisoner search.
Hopefully moving to prisoner API should remove the race condition.  If it doesn't then we will have to revisit this.
=> SAA-1412 using prison API in favour of prisoner search in effort to avoid a race condition when looking up merged prisoner details in prisoner search.

helm_deploy/hmpps-activities-management-api/values.yaml, helm_deploy/values-dev.yaml, src/main/resources/migrations/common/V2023.12.15__add_index_to_local_audit.sql
Also improving indexing on the local audit table which the offender merge process will use when retrieving and updating prisoner audit records.
=> SAA-1412 enable offender merge updates in preprod and prod.

src/main/resources/application.yml
There are two changes here:
1. Adjust connection pool size, idle time and wait times so that it will grow to cater for high-activity during migrations.
2. Set the queue admin role to ROLE_ACTIVITY_QUEUE_ADMIN that we can give to our personal clients.
=> SAA-1415: Connection pool settings to cater for high load during migrations.

src/main/resources/logback-spring.xml
If you look at the console output when the service starts you can see the logging configuration was not being picked up.
The way in which the console appender is configured has changed since we inherited the original from the Kotlin template.
=> SAA-1456 correcting the console appender should now mean the configuration is picked up correctly and not falling back to the Spring Boot default.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/InterestingEventHandler.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/InboundEventsIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/InterestingEventHandlerTest.kt
The interesting event handler has been requesting full prisoner information from prison-api when it doesn't actually need it.  
The impact of doing so means prison-api has to do a lot more work in terms of servicing the requests here.
This change means we are asking for minimal information which in turns reduces the load on an already heavy hit prison-api.
=> SAA-1480 reducing the data requested (and load) from prison API in the interesting event handler as we don't need the extra information.

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/common/LocalDateExt.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityScheduleController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityScheduleService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/common/LocalDateExtTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/ActivityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/TimeSource.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityScheduleIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/AppointmentJobIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ManageAllocationsJobIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityScheduleControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityScheduleServiceTest.kt, src/test/resources/test_data/seed-reduced-activity-instances.sql
This should be viewed as a short to medium term (temporary??) solution to limit the overall size of a schedule and its associated instance child entities (which in turn have attendances associated with each instance).
This change adds an optional filter to the existing GET /schedules/{id} for the earliest point at which instances should be included in the response.
Note the potential gotcha here is if there are no recent instances that fit within the current time window (schedule no longer active/running) then they will be empty on the returned schedule.
=> SAA-1493 interim solution to prevent overly large schedules being returned when looking up a schedule by its ID.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/config/WebClientConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityScheduleService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/client/casenotesapi/api/CaseNotesApiClientTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/ActivityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityScheduleServiceTest.kt
Fixes a bug I introduced whereby we used to be able to allocate a prisoner when they are either active in or out of a given prison.
=> SAA-1495 should be able to allocate prisoners to an activity when they are active in or out of the prison in question.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Appointment.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AppointmentSeries.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AppointmentSet.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AppointmentUpdateDomainService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/Appointment.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/AppointmentDetails.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/AppointmentSummary.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/DailyAppointmentMetricsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AppointmentCancelDomainServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AppointmentSeriesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AppointmentSetTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AppointmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/AppointmentModelFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/AppointmentDetailsIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/AppointmentIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/AppointmentJobIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/AppointmentSeriesIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/AppointmentSetIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/MigrateAppointmentIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/AppointmentTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AppointmentSeriesServiceTest.kt
This will make deleted appointments retrievable through our service while flagged as deleted. This allows us to show where appointments have been deleted from an appointment series/set and allows the user to view the archived details of the appointment such as who deleted it and when.
This has no impact on NOMIS sync where deleted appointments will remain deleted. Similarly, deleted appointments will continue to be hidden from unlock lists and the appointment search dashboard.
=> SAA-1504: Show deleted appointments with `isDeleted` flag

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityController.kt
This flags the GET activities/{ID} as deprecated with the plan to remove it in the near future once we are happy it is no longer used.
=> SAA-1536 deprecated heavy hitting endpoint with the plan to remove when given all clear.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/SarAllocation.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/SubjectAccessRequestContent.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/SarRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/Roles.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/SubjectAccessRequestController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/SubjectAccessRequestService.kt, src/main/resources/migrations/common/V2024.02.07__create_subject_access_request_allocations_view.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/MigrateAppointmentIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/SubjectAccessRequestIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/SubjectAccessRequestControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledInstanceServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/SubjectAccessRequestServiceTest.kt, src/test/resources/test_data/seed-subject-access-request.sql
The is the first attempt and introducing an endpoint for subject access requests in the service.
The first cut only provides allocations data. We still need attendances, waiting lists and appointments to be included.
This does however provide the bulk of the framework needed to add in the other required data.
The use of SQL views is intentional to avoid potential costly JPA queries.  It also helps keep the SARs code completely separate.
Note if you want to run/test this locally you will need the appropriate SAR role in your personal dev client credentials (if you have them).  The activities client does not and should not have this role.
=> SAA-1528 new endpoint to surface prisoner data for subject access requests.

src/main/resources/migrations/common/V2024.02.08__wakefield_configuration.sql
Set the regime times.
Set the rollout prison - false for activities and appointments (we'll update these in each env manually)
Set the standard pay bands 1-10
=> Rollout configuration for Wakefield setup for the 16th Feb

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/SarAllocation.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/SubjectAccessRequestContent.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/SarRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/SubjectAccessRequestService.kt, src/main/resources/migrations/common/V2024.02.13__add_allocation_date_subject_access_request_allocations_view.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/SubjectAccessRequestIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/SubjectAccessRequestServiceTest.kt, src/test/resources/test_data/seed-subject-access-request.sql
API endpoint GET /subject-access-request/prisoner/{prisonerNumber}
change the from and to date search for allocations to be based on the allocation creation date.
=> SAA-1528 - subject-access-request base allocation searches on allocation time for the from and to date

build.gradle.kts, helm_deploy/hmpps-activities-management-api/templates/manage-allocations-deallocate-ending-cronjob.yaml, helm_deploy/hmpps-activities-management-api/templates/manage-allocations-deallocate-expiring-cronjob.yaml, helm_deploy/hmpps-activities-management-api/values.yaml, helm_deploy/values-dev.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/common/LocalDateExt.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/common/LocalTimeExt.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/config/WebMvcConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivitySchedule.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Allocation.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/ManageAllocationsJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/ManageAttendanceRecordsJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/SafeJobRunner.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/ActivityScheduleRepositoryCustom.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/JobTriggerController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ManageAllocationsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/common/LocalDateExtTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityScheduleTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AllocationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/ActivityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/DailyActivityMetricsJobIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ManageAllocationsJobIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/ManageAllocationsJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/ManageAttendanceRecordsJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/JobTriggerControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ManageAllocationsServiceTest.kt, src/test/resources/test_data/seed-activity-id-11.sql, src/test/resources/test_data/seed-activity-id-12.sql
This reverts this [revert](https://github.com/ministryofjustice/hmpps-activities-management-api/pull/767) with the addition of a small change to the time restrictions for deallocation of offenders
=> SAA-1510: Allow allocations due to end job to de-allocate from yesterday

src/main/resources/migrations/common/V2024.02.16__remove_unique_index_from_allocations.sql
This index was added to prevent duplicate allocations to the same activity, however this has had a knock on effect with deallocation
We have since found that an offender can be allocated to the same activity on the same date provided the earlier one is already ended, however if you then try to end the later allocation a duplicate key violation is incurred.
This is causing issues the deallocate expiring allocations job.
=> SAA-1561 removing index originally introduced to help prevent duplication submission of allocations as this is impacting deallocations.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/ManageAllocationsJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/ActivityScheduleRepositoryCustom.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ManageAllocationsService.kt, src/main/resources/application.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ManageAllocationsJobIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/ManageAllocationsJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ManageAllocationsServiceTest.kt, src/test/resources/test_data/seed-activity-id-28.sql
- Add time window to deallocate ending job to cover that failed for previous runs within the window, e.g. 3 days.
- Remove use of session filter
=> SAA-1510: Add time window to deallocate by ending job

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ManageAllocationsService.kt
This bug was introduced by me when reworking the job.
The change fixes the issue where the allocation amended event was being published before the allocation end had been committed to the DB.
This now publishes the allocation amended event after the change has been saved to the database.
Not sure how to test this other than manually looking at commits in log output at the moment, it not easy to cover in a unit test.
=> SAA-1577 fixing issue whereby event was being published before being committed to DB when deallocating offenders due to end on activities.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/SubjectAccessRequestData.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/SubjectAccessRequestService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/SubjectAccessRequestIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/SubjectAccessRequestServiceTest.kt
The SAR response object was not conforming to the API specification and was missing the root node 'content'.
All SAR data should be in the root node as follows below:
```
{
content: { .. data goes here ... }
}
```
=> SAA-1578 adds the missing root node 'content' to the SAR response object.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AppointmentUpdateDomainService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AppointmentSetService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AppointmentUpdateDomainServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/AppointmentIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/AppointmentSeriesIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/AppointmentSetIntegrationTest.kt
- Classify in cell appointments as on wing
- Classify internal location as off wing 
- Ensure appointment creation to handle In Cell
- Ensure appointment Set creation to handle In Cell
- Ensure appointment Series creation to handle In Cell
=> SAA-1559: Classify in cell appointments as on wing

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/config/WebMvcConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/ManageAttendanceRecordsJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/SafeJobRunner.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/RetryConfigurationIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/AppointmentMetricsJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/CancelAppointmentsJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/CreateAppointmentsJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/CreateScheduledInstancesJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/DeleteMigratedAppointmentsJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/ManageAllocationsJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/ManageAppointmentAttendeesJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/ManageAttendanceRecordsJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/SafeJobRunnerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/UpdateAppointmentsJobTest.kt
This PR adds the ability to retry a block of code by providing a reusable Spring Bean.
The need for this arose due to the fact the morning attendance job failed due to an issue calling an external service. Whilst we can manually re-run ideally we would like to retry to avoid the need to get a developer involved to re-run the failed job.
This can easily be applied to other areas of the code base e.g. other jobs.
=> SAA-1579 changes to allow the attendance creation job to retry a maximum of 4 times before accepting failure.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Allocation.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ManageAllocationsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityScheduleTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AllocationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AuditableEntityListenerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/CandidatesServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/AuditTransformationsTest.kt
The logic for dellocation has changed.
We need to allow a date to be supplied upon deallocation to support back dating deallocations.
This was spotted when dellocated allocations were not using the planneded deallocation reason due to dates being out of sync e.g. actual deallocation of allocation for yesterday was happening today but the planned deallocation was for yesterday.
=> SAA-1598 change to allow a date to be passed through upon deallocation to allow for the deallocation to be back dated.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/WaitingListApplication.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityScheduleService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/WaitingListService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctions.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/ActivityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityScheduleIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/WaitingListApplicationIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityScheduleControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/WaitingListApplicationControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityScheduleServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/WaitingListServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctionsTest.kt
The /schedules/{scheduleId}/waiting-list-applications needs to include the earliest release date as this is required to be shown on the Waitlist on Activity Allocation screen
=> SAA-1572: add earliest release date to waiting list applications

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Allocation.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/SafeJobRunner.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AllocationTest.kt
This bug was spotted after the deallocation job failed and the attendance job ran successfully (in DEV)
An allocation that should have been ended due to having a planned end date did not end but an attendance record was still created when it shouldn't have been.  This was because it did not factor in the allocations planned end date.
=> SAA-1619 logic for canAttendOn(...) on Allocation was not factoring the planned allocation end date.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ManageAllocationsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ManageAttendancesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ManageScheduledInstancesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/MonitoringService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ManageAllocationsServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ManageAttendancesServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ManageScheduledInstancesServiceTest.kt
Exceptions raised in some of the jobs are being missed due to the nature of `try ... catch` (and not propagating).
To be clear the `try ... catch` was always intentional e.g. if attendance creation fails for one prison doesn't mean it should fail for all.
In these scenarios the jobs can complete as successful even if there were some errors during the run.  If that does happen this change should at least provide some better visibility by essentially creating a Sentry alert which will propagate to the team alerts channel.
=> SAA-1626 adding Sentry monitoring for caught exceptions in jobs so don't go unnoticed.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/InboundEvents.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/EventsFactory.kt
End to end testing in dev confirms this alert was never tested, the structure of the message we were expecting was not correct.
This change should clean up a message we have sitting on our DLQ in dev.
Note preprod and prod are not affected as we are not listening for this event in those envs.
=> SAA-1629 correcting the prisoner alert payload, personReference is not part of the payload, nomsNumber is though.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/config/CacheConfiguration.kt
Increase the Bank Holiday Service Cache to only evict every 7 days rather than every day.
The Bank Holiday service failed during the Activity Schedule Job overnight calling the bank holiday service. As this does not change often this change will call it much less frequently and use the cached copy.
To test the same config was used, but with seconds rather than hours. You can see the output below where the 2 caches prisoner incentive and bank holidays evict at the different times.
`2024-03-25 14:33:49.121  INFO 22056 --- [           main] u.g.j.d.h.h.h.VersionOutputter$Companion : Version 2024-03-25 started |  
2024-03-25 14:34:13.055  INFO 22056 --- [   scheduling-1] g.j.d.h.h.c.CacheConfiguration$Companion : Evicting cache: prisonIncentiveLevels after 24 seconds |  
2024-03-25 …
=> SAA-1639 increase bank holiday service cache to expire every 7 days

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/ScheduledInstanceRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityScheduleInstanceController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledInstanceService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityScheduleInstanceIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/CreateScheduledInstancesJobIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityScheduleInstanceControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ManageAttendancesServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledInstanceServiceTest.kt, src/test/resources/test_data/seed-activity-id-3.sql
For daily attendance summary the UI retrieves all scheduled instances and filters them to leave the cancelled ones.  This means that we get a bad N+1 JPA effect and the UI can time out  as it waits for the API. We can shift the logic to the repo so only the cancelled scheduled instances are retrieved which will make the UI more responsive.
=> SAA-1509: Allow scheduled instances to filtered by cancelled status

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/request/AppointmentSeriesCreateRequest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/request/AppointmentSeriesCreateRequestTest.kt
Change the create an appointment request API to allow retrospective appointments to be created. The API now allows appointments to be created for 5 days in the past.
=> SAA-1656 create retrospective appointments

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Attendance.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AttendanceSuspensionDomainServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AttendanceTest.kt
Implement the following rules on when attendance has can be recorded/changed:
If attendance has been recorded as attended or not attended & paid, stop any changes after the day the attendance was recorded
If attendance has been recorded as not attended & unpaid, changes can only be made for 7 days after the activity date
If attendance has not been recorded, the user can record attendance up to 14 days after the activity date
=> SAA-1688: Correct Activity Attendance Editing to Match NOMIS Constraints

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/PrisonRegime.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctions.kt
This is so the UI can determine that the prisoner's movement where they have left the prison occurred `x` days ago depending on the prison's `maxDaysToExpiry` value.
=> SAA-1655: Add max days to expiry to regime endpoint DTO

build.gradle.kts
Reverts ministryofjustice/hmpps-activities-management-api#881 because deploy [is broken](https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-activities-management-api/4891/workflows/27343d50-1122-4087-8f4b-7a44cafdd3d0/jobs/17014?invite=true#step-114-5573_142)
=> Revert "Update plugin io.sentry.jvm.gradle to v4.6.0"

.circleci/config.yml, build.gradle.kts
Reverts ministryofjustice/hmpps-activities-management-api#890
Fails to build Docker image as [out of mem](https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-activities-management-api/4921/workflows/9dc0107d-aa11-4b4b-8c6d-ec7ee330c225/jobs/17137?invite=true#step-111-21903_75)
=> Revert "Update plugin org.jetbrains.kotlin.plugin.spring to v2"

src/main/resources/migrations/prod/V2024.05.30__fix_cancelled_in_error_appointments.sql
Need to mark the future appointments for an appointment series as deleted as they were created in error, not cancelled and appear on the unlock list.
=> SAA-1759: Need to mark the future appointments for an appointment series as deleted appointments

.circleci/config.yml, build.gradle.kts, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityScheduleIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/AppointmentIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/AppointmentJobIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/config/FeatureSwitchesTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/config/PostgresContainer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/entity/AuditableEntityListenerTest.kt, src/test/resources/application-test.yml, src/test/resources/test_data/clean-all-data.sql, src/test/resources/test_data/event-review-data.sql, src/test/resources/test_data/seed-activity-id-11.sql, src/test/resources/test_data/seed-allocations-due-to-expire.sql, src/test/resources/test_data/seed-attendances-two-days-old-waiting.sql, src/test/resources/test_data/seed-attendances-yesterdays-completed.sql, src/test/resources/test_data/seed-attendances-yesterdays-waiting.sql, src/test/resources/test_data/seed-offender-merged-event-old-and-new-allocations.sql
Replaced H2 with Postgres for integration tests.
Will use TestContainers locally unless there is already a Postgres DB on port 5432 in which case it will try to use that so maybe remap your port in [docker-compose.yml](https://github.com/ministryofjustice/hmpps-activities-management-api/blob/main/docker-compose.yml#L10).
CircleCI uses [java_postgres](https://circleci.com/developer/orbs/orb/ministryofjustice/hmpps#executors-java_postgres) orb to spin up postgres and then [waits for it](https://circleci.com/developer/orbs/orb/ministryofjustice/hmpps#commands-wait_till_ready_postgres) before running tests.
There were a few tests that were unnecessarily strict on ordering of lists so I have fixed those **but some more may arise**.
=> SAA-1751: replace h2 with test containers postgres for integration tests

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Attendance.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AttendanceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityScheduleInstanceIntegrationTest.kt, src/test/resources/test_data/seed-activity-id-29.sql
Creating attendance records for cancelled activity use cancelled time for the attendance recorded time. Need to allow attendance records to be edited for uncancelling an activity on the day
=> SAA-1801: cancelled activity attendance recording

src/main/resources/migrations/common/V2024.06.26__external_service_appointment_cancellation_reason.sql
BVLS is using the activities API to create video bookings when bookings are made in BVLS to keep the two services in sync.
When an appointment is cancelled in BVLS we also need to cancel the video booking in activities and appointments. In doing so we also need the appointment deleted.
To support this we thought a more appropriate cancellation reason would be needed as 'cancelled in error' does not really fit.
Cancellation reasons are not shared in the UI so this change should be safe.
=> BAVL-213 adds new appointment cancellation reason for cancellations via an external service.

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/OffenderMergedEventHandler.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/ActivityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/InboundEventsIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/InmateDetailFixture.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/events/handlers/OffenderMergedEventHandlerTest.kt
Will handle merge event from all prisons not just rolled out ones.
Will not add to `event_review` table unless prison is rolled out
=> SAA-1823: Handle merge events from all prisons

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/client/adjudications/AdjudicationsHearingAdapter.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledEventService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/client/adjudications/AdjudicationsHearingAdapterTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ScheduledEventIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledEventServiceMultiplePrisonersTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledEventServiceSinglePrisonerTest.kt
code was always passing 2 days range for some reason to prison api, inherited by adjudications now
=> SAA-1885 bug fix, date range is wrong for adjudications

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Activity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityPay.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivityPay.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/request/ActivityCreateRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/request/ActivityPayCreateRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/request/ActivityUpdateRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/MigrateActivityService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctions.kt, src/main/resources/migrations/common/V2024.07.18__add_activity_pay_start_date.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityPayTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AllocationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/ActivityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/request/ActivityCreateRequestTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/request/ActivityUpdateRequestTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ManageAttendancesServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledInstanceServiceTest.kt, src/test/resources/__files/activity/activity-update-request-7.json, src/test/resources/application-test.yml
Include getting the current dates pay rate and storing in the database
=> SAA-1750: Add start date to the activity pay to allow a future date changes for an activity pay rates

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivitySchedule.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Allocation.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Exclusion.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/request/AllocationUpdateRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/request/PrisonerAllocationRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityScheduleService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AllocationsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ManageAttendancesService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityScheduleTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AllocationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/ActivityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityScheduleIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/AllocationIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/PrisonIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/request/AllocationUpdateRequestTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/request/PrisonerAllocationRequestTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityScheduleServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AllocationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ManageAttendancesServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/MigrateActivityServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledInstanceServiceTest.kt, src/test/resources/test_data/seed-activity-id-1.sql, src/test/resources/test_data/seed-activity-id-7.sql
Allow a new allocation to happen for a session(s) today indicated by the user choosing the scheduled instance in the UI.
Similar for update an allocation.
If prisoner can attend the sessions then new activities will be created and messages posted for synch.
This can also work for sessions earlier in the day should the user dawdle in the UI
=> SAA-1887: Allocate to a session running today

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/request/AppointmentSearchRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/appointment/AppointmentSearchService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/AppointmentSearchIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/request/AppointmentSearchRequestTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/AppointmentControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AppointmentSearchServiceTest.kt, src/test/resources/test_data/seed-appointment-search.sql
Resolves the day of week, for regime times, when timeslots passed in.  Issue is a date range, and different regime times not compatible in current code pattern
The endpoint request has startDate as not null, yet declared as nullable, with tests for some reason around  json, bizarre.
removing the end date, as its optional, our UI does not use it
It is being used by BAVL but will get picked up by openApi next time they generate, and they are using the same date for start and end anyway, no need to pass end.
=> SAA-1948 start date only, day of week

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivitySchedule.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/ActivityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityServiceTest.kt
When updating an activity:
- set `onWing`, `offWing` and `inCell` to false when changed to internal location
- set internal location details to `null` when changing to `onWing`, `offWing` or `inCell`
=> SAA-2004: Set correct location details for activity when updating

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/Activity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivitySchedule.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ScheduledInstance.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/ScheduledInstanceRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ScheduledInstanceController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AttendancesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledInstanceService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ActivityTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/ActivityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityScheduleInstanceIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/AttendanceIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledInstanceServiceTest.kt, src/test/resources/test_data/seed-activity-id-1.sql
- Add new POST endpoint to accept schedule instance ids and return them all in one go
- Avoid adding irrelevant allocation details in the response model
- Add `JOIN FETCH` to repo query to improve performance
=> SAA-2067: Improve speed of retrieving scheduled instances for multiple attendances

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/request/ActivityMigrateRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/MigrateActivityService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/MigrateIntegrationTest.kt
Add TimeSlot to the migrate activity service Nomis Schedule Rule and use this if it supplied to set the TimeSlot for the activity schedule slot
=> SAA-2110: Add TimeSlot to the migrate activity service

src/main/resources/migrations/prod/V2024.10.31__gartree_appts_undelete.sql
Undeletes some mistakenly deleted appointments for Gartree, 192 in total. 
Once done, Syscon will re-play the create events for these appts so NOMIS will remain in sync
=> undelete gartree future appts

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/AttendanceRepository.kt, src/test/resources/test_data/seed-activity-id-27.sql
There is a bug in the attendance reconciliation where a prisoner is deallocated from an activity and then reallocated on the same day (and then attended and marked with pay). The problem is that both allocations are considered "active" and so the attendance is counted towards the count twice. To fix we make sure the attendance is only counted once.
To find an example of the bad data run SQL `select * from allocation a where booking_id = 2694358 and activity_schedule_id = 553;` This scenario has been emulated in the test data for `seed-activity-id-27.sql`.
=> SDIT-2238 Fix attendance reconciliation bug

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/MigrateActivityService.kt
Already uses a transaction handler. test in pre-prod
=> disable transactional annotation for migrating activity and allocation. 

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/config/WebClientConfiguration.kt
Reduce prison-api timeout to 10 seconds allowing it to retry within the normal 30s UI timeout for example.
=> SAA-2208: Use shorter timeout for prison api

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/PrisonerScheduledActivityRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/InternalLocationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/MigrateActivityService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/LocationIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/MigrateIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ScheduledEventIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/InternalLocationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/MigrateActivityServiceTest.kt, src/test/resources/test_data/seed-activity-id-3-on-wing.sql
3 changes:
- If migrating an activity which has a location id and a location code containing "WOW" then do not set the location id but do set on-wing to true
- When viewing movement list locations do not included activities that are both on-wing and have a location id
- When viewing movement list items remove any that are both on-wing and have a location id.
:warning: **There are ~500 activities which are on-wing and have a location id - there are no plans to fix the data**
=> SAA-2239: Default to on-wing if activity also has location id

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/RolloutPrisonPlan.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/refdata/RolloutPrisonService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/RolloutPrisonTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/ActivityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/RolloutIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/ManageAttendanceRecordsJobTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/RolloutPrisonPlanTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/RolloutControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ManageScheduledInstancesServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/MigrateActivityServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledEventServiceMultiplePrisonersTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledEventServiceSinglePrisonerTest.kt
Add a new parameter to the rollout response for identifying a prison is live to users
Deprecate the rollout dates for activities and appointments (Need to update the frontend before removing)
Still to do is to add a live prison filter to the /rollout endpoint and remove the rollout dates
=> SAA-2282: Add a new parameter to the rollout response for identifying a prison is live to users

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/ScheduledInstance.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/Attendance.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/ScheduledInstanceRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ManageAttendancesService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ActivityScheduleIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/AttendanceIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ManageAttendanceRecordsJobIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ManageAttendancesServiceTest.kt, src/test/resources/application-test-local-stack.yml, src/test/resources/application-test.yml, src/test/resources/test_data/seed-activity-id-7.sql
Only add attendance records for the scheduled instances today when allocating a new prisoner. Make attendance history optional
=> SAA-2278: Change the Scheduled Instance attendance to lazy load. 

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/PurposefulActivityRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/PurposefulActivityService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/PurposefulActivityIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/PurposefulActivityServiceTest.kt
The original code caused OOM in Pre-prod.
The new changes use a stream to fetch the data from DB.
Code is a bit "hacky" but will be replaced by DPR in time.
=> SAA-1785: Reduce memory used by purposeful activity report

.circleci/config.yml
Created new [activities-and-appointments-alerts-security](https://moj.enterprise.slack.com/archives/C08BVFF9TFG) channel for security alerts
Moved release alerts to dev channel as per guidance https://tech-docs.hmpps.service.justice.gov.uk/creating-new-services/prerequisites/
=> SAA-2327 update circle ci alerts channels

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/appointment/AppointmentService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/appointment/AppointmentSetService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/appointment/MigrateAppointmentService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/MigrateAppointmentIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AppointmentServiceUpdateTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AppointmentSetServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/MigrateAppointmentServiceTest.kt
- Prevent new and updated appts from having start date more than 370 days in future
- Fix migration to reject any appointments which start over 370 days in future **but not if category code is BVLS**
=> SAA-2331: Prevent appointments for having start date too far in future

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/MigrateActivityService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/MigrateActivityIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/MigrateActivityServiceTest.kt, src/test/resources/test_data/seed-activity-id-23-2.sql
For migrating allocations start dates use the activity start date or allocation start date. Whichever is further in the future
=> SAA-2344: Allocation start date migration

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/repository/ActivityScheduleRepository.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/UtilityController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ActivityLocationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/UtilityIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/UtilityControllerTest.kt, src/test/resources/test_data/seed-activity-id-34.sql
Utlity endpoint to list activities with invalid locations:
```
Prison Code,Activity ID,Activity Description,Internal Location ID,Internal Location Code,Internal Location Description,DPS Location ID
LEI,79,C Wing cleaning,14444,CWING,C Wing,84852b74-7d91-4267-97f7-476befc73776
LEI,78,C/D Wing laundry,14444,CWING,C Wing,84852b74-7d91-4267-97f7-476befc73776
LEI,80,C Wing - Orderly,14444,CWING,C Wing,84852b74-7d91-4267-97f7-476befc73776
LEI,1110,RECEPTION CLEANERS,14528,RECEP,Reception,7bfef4ed-c58b-4fbf-809d-bf62040fd00a
LEI,678,RECEPTION CLEANERS,14528,RECEP,Reception,7bfef4ed-c58b-4fbf-809d-bf62040fd00a
```
=> SAA-2427: Add endpoint to list activities with invalid locations

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/InternalLocationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/helpers/ActivityFactory.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/InternalLocationServiceTest.kt
If a prisoner is deallocated from today and there are sessions later today then they will appear on the movement list for today.
As part of deallocation the API will remove the relevant attendance records for today.
Use the fact that there are no attendance records and that movement list is for today to filter out those prisoners.
NB: Attendance records are only create for one day.
=> SAA-3333: Ignore activity prisoners from movement list de-allocated from sessions later today

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledEventService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ManageAttendanceRecordsJobIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ScheduledEventIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ScheduledEventServiceMultiplePrisonersTest.kt, src/test/resources/test_data/seed-activity-for-attendance-job.sql, src/test/resources/test_data/seed-activity-with-planned-deallocation-date.sql
If a prisoner is deallocated from today and there are sessions later today then they will appear on the unlock list for today.
As part of deallocation the API will remove the relevant attendance records for today.
Use the fact that there are no attendance records and that unlock list is for today to filter out those prisoners.
NB: Attendance records are only create for one day.
=> SAA-3333: Ignore activity prisoners from unlock list deallocated from sessions later today

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/AttendanceCreationData.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ManageAttendancesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/util/TransformFunctions.kt, src/main/resources/migrations/common/R__v_attendance_creation_data.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ManageAttendanceRecordsJobIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/ManageAttendancesServiceTest.kt, src/test/resources/test_data/seed-activity-with-advance-attendances-1.sql
A user can create advance attendances to say that a prisoner is not required for a future activity.
On the morning of that day the attendance job needs to check for any advance attendances for that prisoner and that session and create the not required attendance record.
Example UI:
=> SAA-2444: Create not required attendance records

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/model/ActivityScheduleLite.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/resource/ActivityController.kt
Contains some corrections to the OpenAPI schema annotations for the `/activities/{activityId}/schedules` endpoint.
=> Correct activity schedules OpenAPI schema

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/appointment/AppointmentManagement.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/appointment/AppointmentAttendeeService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/entity/appointment/AppointmentManagementTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/InboundEventsIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/AppointmentAttendeeServiceTest.kt, src/test/resources/test_data/seed-appointments-changed-event.sql
Related [Jira](https://dsdmoj.atlassian.net/browse/BAVL-1030) ticket.
This change stops attendees from being removed from video link court and probation appointments. These appointment types are (now) managed outside of A&A via the book a video link service.
For example, when a prisoner is released the appointment is cancelled by the book a video link service making a call the A&A API.  A&A should not take any further action for these appointment types on the release of prisoners.
=> BAVL-1030 attendees should not be removed from court and probation video appointments

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/ManageAllocationsJob.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/service/WaitingListService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/AbstractJobIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/CreateScheduledInstancesJobSqsIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/LocalStackTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/integration/ManageAllocationsJobSqsIntegrationTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsactivitiesmanagementapi/job/ManageAllocationsJobTest.kt
- Job type fixed to use `DEALLOCATE_ENDING` instead of `SCHEDULES`
- Refactoring and improving tests
=> SAA-3537: Fix job type saved to database for deallocate allocations due to end
